### ISSUE TITLE
Server production bundle not created

### ISSUE THREAD

**Issue by lewebsimple** [antfu/vite-ssg#1]
Maybe I'm missing something, but it seems the production bundle is not created when building the project (no folder named .vite-ssg-dist/)

I tried a clean vitesse project and get the same problem : no server production bundle !

**Comment by antfu** [comment]
`.vite-ssg-dist` is a temporary folder for SSG and will be removed after the build. Please note SSG is note SSR which does not have a server bundle. You may want to use vite-ssr for it. https://github.com/frandiox/vite-ssr
