### ISSUE TITLE
Critical CSS critters package causing linting errors

### ISSUE THREAD

**Issue by lobo-tuerto** [antfu/vite-ssg#100]
Hello,
I just added ViteSSG to an existing Vite + Vue 3 + TypeScript app, but unfortunately when linting the app with `vue-tsc --noEmit` I get this output:

```bash
$ vue-tsc --noEmit
node_modules/vite-ssg/dist/types-5566f955.d.ts:4:25 - error TS2307:
Cannot find module 'critters' or its corresponding type declarations.

4 import { Options } from 'critters';
                          ~~~~~~~~~~


Found 1 error.
```

It this something that needs fixing on ViteSSG's side?

Note: If I skip the linting step and build directly with `vite-ssg build` it builds just fine.

**Comment by antfu** [comment]
I would suggest adding `"skipLibCheck": true` to your `tsconfig.json`

**Comment by lobo-tuerto** [comment]
Thanks, that worked and also sped up the linting process by a lot. :tada:
