### ISSUE TITLE
Can I just build client-side only? No SSR.

### ISSUE THREAD

**Issue by alstoncao** [antfu/vite-ssg#101]
I'm using vitesse and one of the 3-rd party library (element-ui 3) use `document` variable, it will build fail with a not defined error. Since it's just an admin page, I don't need SSR, a client-side only render would be fine. How to config it to render client  side only?

ps. I've turned on the `mock` option but not working, still `ReferenceError: document is not defined`.
```
ssgOptions: {
    script: 'async',
    formatting: 'minify',
    mock: true,
  },
```

Thanks

**Comment by userquin** [comment]
`vite-ssg` will always use ssr on build, and so you cannot use deps that are not ssr/ssg aware with import.

If you use `ClientOnly` the import is still there and so your build will fail. You need to import those deps with dynamic import.

**Comment by antfu** [comment]
Not sure if I got your point. If you don’t need SSR, you don’t actually need this plugin 👀

**Comment by Adam-512** [comment]
> Not sure if I got your point. If you don’t need SSR, you don’t actually need this plugin 👀

Actually i want a config option like 'ssr:false' in ViteSSG too. So that to skip build for server

**Comment by Adam-512** [comment]
@antfu

**Comment by antfu** [comment]
Remove this package and you can build the client only.

**Comment by u007** [comment]
we want the functionality like how nuxt3 component.client.vue works, 
so it will not render the component on ssg but still runs on client side
