### ISSUE TITLE
Allow Configuring Scroll Behavior

### ISSUE THREAD

**Issue by Uninen** [antfu/vite-ssg#102]
It would be nice to be able to configure Scroll Behavior for the router as per the docs: https://next.router.vuejs.org/guide/advanced/scroll-behavior.html

**Comment by hannoeru** [comment]
https://github.com/antfu/vite-ssg#install

The second argument of `ViteSSG` is `vue-router`'s options

**Comment by Uninen** [comment]
Duh, I think I need to stop coding at night 😅

Sorry for the noise, and thanks! 👍
