### ISSUE TITLE
Single Page Support

### ISSUE THREAD

**Issue by santicros** [antfu/vite-ssg#11]
Hi!! I think it's really awesome to have SSG on Vite, thanks for your work.
One thing I would love to have is not to require Vue Router by default. I'm building a complex Landing Page site with multiple components, but it's only one page, so I don't use Vue Router.
Now, if I don't have installed Vue Router or I don't have routes configured it's failing. Could this be optional?

Thanks again!

**Comment by antfu** [comment]
Supported in v0.6.x

**Comment by santicros** [comment]
Thanks a lot for the super fast update @antfu !!!
