### ISSUE TITLE
Using specified config file

### ISSUE THREAD

**Issue by ttxtosca** [antfu/vite-ssg#111]
Hello,

`vite-ssg` is working for me as expected (until now :).

Nevertheless, I would appreciate (a lot) that vite-ssg can have an option like `vite`'s one :

`-c, --config <file>     [string] use specified config file`

Do you think that is possible? If it already exist (trick or so), can you explain?

It's for context of monorepos / pm2 deploys, at build, where config file isnt in `cwd` but `makefile` is (at root).

Thanks for this package!

**Comment by userquin** [comment]
@ttxtosca if you want to play with it, clone this repo: you can take a look a `src/node/cli.ts` (this is the cli module) and `src/node/build.ts`: adding the option on former and just use it from `cliOptions` on later, you'll need to read it if present and then provide the configuration read as the first argument here:
[`const config = await resolveConfig({}, 'build', mode)`](https://github.com/antfu/vite-ssg/blob/main/src/node/build.ts#L29).

You can see `vite cli`:
- https://github.com/vitejs/vite/blob/main/packages/vite/src/node/cli.ts#L16
- https://github.com/vitejs/vite/blob/main/packages/vite/src/node/cli.ts#L58
- https://github.com/vitejs/vite/blob/main/packages/vite/src/node/cli.ts#L166

Maybe you need to change some arguments on the build calling `viteBuild`.

PR welcome.

**Comment by ttxtosca** [comment]
Thanks for reply. I'll check when I have some time! Will for sure produce PR if I have something :)

Feel free to close this ticket if you think this is not a "very required" feature and/or if none of maintainers have time to make this option.

**Comment by 634750802** [comment]
As a workaround:
```json
{
 "scripts": {
    "dev": "vite -c vite.config.prod.ts",
    "build": "cp vite.config.prod.ts vite.config.ts && vite-ssg build && rm vite.config.ts",
    "build:preview": "cp vite.config.preview.ts vite.config.ts && vite-ssg build && rm vite.config.ts"
  }
}
```
