### ISSUE TITLE
TypeError: createApp is not a function

### ISSUE THREAD

**Issue by rossjrw** [antfu/vite-ssg#112]
This is a solved problem - I'm just making an issue here so that hopefully someone experiencing this issue in the future will see it.

I was encountering a persistent error when trying to run the build process: `TypeError: createApp is not a function` just after producing the server build. By fiddling with the compiled package code I was able to trace it back to this line:

https://github.com/antfu/vite-ssg/blob/c2752aa65c21db8deff969b3d19927aa46e2182a/src/node/build.ts#L89

This is the part where vite-ssg imports the exported `createApp` from the app entrypoint on the server side. Adding some logging here revealed that the import was actually totally empty, so `createApp` did not exist.

I looked in my server bundle (which had not been cleaned up because the vite-ssg build crashed) to find the compiled entrypoint (in my case `src/.vite-ssg-temp/main.js`), scrolled to the bottom, and saw the `ViteSSG` function being called, but not exported - there was no export statement.

My `main.ts`, exporting to `const createApp` per this repo's instructions:

```ts
import { ViteSSG } from "vite-ssg/single-page"
import { App } from "./components/App.vue"

export const createApp = ViteSSG(App)
```

had been compiled to:

```js
singlePage.ViteSSG(App)
```

Not exported, not even assigned to `createApp`.

It took me a while and some discussion with other frontend developers, including @ljharb, to work out what was happening here. We concluded that rollup had 'intelligently' tree-shaken away the export, concluding that it was unused because it was not required by anything else in the bundle. This doesn't make any sense, of course, because an ESM export is supposed to mean 'this will be used elsewhere' and I expected the CJS build to respect that.

I resolved this by preventing tree shaking altogether by adding `treeshake: false` to the rollup config (we don't need it - this is the server-side bundle, so size doesn't matter). This retained the variable assignment:

```js
const createApp = singlePage.ViteSSG(App)
```

...but it still didn't export it!

I resolved this by adding `output.footer = "module.exports = { createApp }"` to the rollup config, which just artificially attaches the export to the end of the bundle. However, if the build produces multiple files (as mine did), this will be added to *all* of them, and only one of them will have `createApp` defined - this will create a reference error, also crashing the build. To avoid that, only add that export if `createApp` is defined (i.e. `typeof createApp !== "undefined"`).

Using the helpfully-added SSG env flag:

https://github.com/antfu/vite-ssg/blob/c2752aa65c21db8deff969b3d19927aa46e2182a/src/node/build.ts#L71

I added the above changes to my Vite config to only be activated during SSG:

```ts
// vite.config.ts
export default {
  [ ... ]
  build: {
    rollupOptions: {
      ...(process.env.VITE_SSG ? { treeshake: false } : {}),
      output: {
        ...(process.env.VITE_SSG
          ? {
              footer:
                "if (typeof createApp !== 'undefined') module.exports = { createApp }",
            }
          : {}),
      },
    },
  },
  ssgOptions: { formatting: "minify" },
}
```

...and now the build and prerender works perfectly.

I have absolutely no idea what causes this issue - I cannot imagine it is anything but a huge, huge flaw in rollup to outright drop an export like this - but this is how you resolve it in this case.

**Comment by u007** [comment]
hi @rossjrw 
i have this in my vite.config.ts, but it still throws error:
```
build: {
    ssrManifest: true,
    rollupOptions: {
      input: {
        main: path.resolve(__dirname, 'index.html'),
      },
      ...(process.env.VITE_SSG ? { treeshake: false } : {}),
      output: {
        ...(process.env.VITE_SSG
          ? {
              footer:
                "if (typeof createApp !== 'undefined') module.exports = { createApp }",
            }
          : {}),
      },
      external: ['node:fs', 'node:path', 'node:url']
    },
  },
```

error:
```
[vite-ssg] An internal error occurred.
[vite-ssg] Please report an issue, if none already exists: https://github.com/antfu/vite-ssg/issues
file:///Users/james/www/sentient/web/node_modules/.pnpm/vite-ssg@0.23.8_vite@5.3.3_@types+node@20.14.10_sass@1.77.8_terser@5.31.2__vue-router@4.4.0_v_46nt5pcuzm537k6vhilatb45xi/node_modules/vite-ssg/dist/node.mjs:1001
  const { routes } = await createApp(false);
                           ^

TypeError: createApp is not a function
    at build (file:///Users/james/www/sentient/web/node_modules/.pnpm/vite-ssg@0.23.8_vite@5.3.3_@types+node@20.14.10_sass@1.77.8_terser@5.31.2__vue-router@4.4.0_v_46nt5pcuzm537k6vhilatb45xi/node_modules/vite-ssg/dist/node.mjs:1001:28)
    at async Object.handler (file:///Users/james/www/sentient/web/node_modules/.pnpm/vite-ssg@0.23.8_vite@5.3.3_@types+node@20.14.10_sass@1.77.8_terser@5.31.2__vue-router@4.4.0_v_46nt5pcuzm537k6vhilatb45xi/node_modules/vite-ssg/dist/node/cli.mjs:34:5)

Node.js v20.10.0
```

**Comment by u007** [comment]
nvm, i realise i need to export const createApp on main.ts
