### ISSUE TITLE
Boolean props shorthand does not work on components

### ISSUE THREAD

**Issue by cimchd** [antfu/vite-ssg#123]
I am not sure which is the right project for this issue. But I encoutered a problem if I use the boolean shorthand for props on components with vite-ssg build.:

This works:
```vue
  <Comp :active="true" />
```
This doesn't:
```vue
  <Comp active />
```

[Link to Vue SFC playground](https://sfc.vuejs.org/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCBDb21wIGZyb20gJy4vQ29tcC52dWUnXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8Q29tcCA6YWN0aXZlPVwidHJ1ZVwiIC8+XG4gIDxDb21wIGFjdGl2ZSAvPlxuPC90ZW1wbGF0ZT4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7XG4gICAgXCJ2dWVcIjogXCJodHRwczovL3NmYy52dWVqcy5vcmcvdnVlLnJ1bnRpbWUuZXNtLWJyb3dzZXIuanNcIlxuICB9XG59IiwiQ29tcC52dWUiOiI8c2NyaXB0IHNldHVwIGxhbmc9XCJ0c1wiPlxuXHRkZWZpbmVQcm9wczx7YWN0aXZlPzogYm9vbGVhbn0+KClcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG5cdDxkaXYgOmNsYXNzPVwiYWN0aXZlID8gJ2FjdGl2ZScgOiAnJ1wiPlxuICAgIFRoaXMgc2hvdWxkIGJlIHJlZFxuICA8L2Rpdj5cbjwvdGVtcGxhdGU+XG5cbjxzdHlsZT5cbiAgLmFjdGl2ZSB7XG4gICAgY29sb3I6IHJlZDtcbiAgfVxuPC9zdHlsZT4ifQ==) for a whole example (the error does not appear in the playground). In dev mode both variants are working.

This is the output of the playground with vite-ssg build:
![image](https://user-images.githubusercontent.com/49520229/139804088-42efedbd-8bfd-40e6-bb69-c867055ddf21.png)
```html
<div class="active">This should be red</div><div class="">This should be red</div>
```

Probably more a vite or vue error?

**Comment by userquin** [comment]
it seems there is a problem with vue, try updating to latest version

https://github.com/vuejs/vue-next/issues/4783
