### ISSUE TITLE
Issue implementing persistent state - browser storage

### ISSUE THREAD

**Issue by techieoriname** [antfu/vite-ssg#127]
Great project I must say, this is one of the most amazing feature that has stormed vite. Kudos `Antfu` and other `Collaborators`.

I'm actually using vite-ssg for a new project, and everything is working out fine.
But I'm curious of how to go about implementing persistent state.

In a nutshell, my store would look like this. While I'm using vue3 reactivity out of the box, and browser-storage (by Trapcode) for handling localStorage data.

``` typescript
import { reactive, readonly } from "vue";
import BrowserStorage from "@trapcode/browser-storage";
// Documentation here https://www.npmjs.com/package/@trapcode/browser-storage
// Initialize
const localStore = BrowserStorage.getLocalStore("namespace");

// Enable Encryption
localStore.enableBase64Encryption(import.meta.env.PROD);

const state = reactive({
    counter: localStore.getNumber("counter", null)
})

function updateCounter($value: number) {
    state.counter = $value
    localStore.setNumber("counter", state.counter);
}

export default {
    state: readonly(state),
    updateCounter
};
```

It's actually difficult importing the Browser Storage package since window object doesn't exist.
Please is there a better approach to implementing this?

**Comment by whoooami** [comment]
Hello @techieoriname , I also encountered local storage problem, can you tell me how you solved it?
