### ISSUE TITLE
Build process question

### ISSUE THREAD

**Issue by kasec** [antfu/vite-ssg#13]
I'm watching your plugin everything works pretty well, a little issue in dev server, I cannot get nested pages.
Other thing, when the app run in HTTP server it redirects just in JS(like spa) and not like proper SSG.

Also, when I tried to build threw me a following error.

```
TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at Function.from (<anonymous>)
    at renderPreloadLinks (/project/node_modules/vite-ssg/dist/node/cli.js:17:9)
```
I have to add default value to `modules = []` param in `renderPreloadLinks` function

reproduction [link](https://github.com/kasec/me/tree/ssg/ssg-vite-example)

I hope you can answer me!

**Comment by Ttou** [comment]
same problem
