### ISSUE TITLE
[Bug] `router.currentRoute` is always root and calling `router.getRoutes()` duplicates routes

### ISSUE THREAD

**Issue by josh-hemphill** [antfu/vite-ssg#138]
I needed to access the nested `meta` tags on each route at build time to set the default language for each route.
On the router provided in `ctx`, I first tried to access `router.currentRoute`, but it was always root, and was otherwise empty.
Now I'm using `router.getRoutes()` and filtering by `routePath` which mostly works but for some reason it creates mostly empty duplicate route entries for each route.

**Comment by gryphonmyers** [comment]
Did you await `router.isReady()`? https://next.router.vuejs.org/api/#isready

**Comment by josh-hemphill** [comment]
That might have been the issue, but if I try making the plugin load function passed to `ViteSSG()` async, it doesn't get awaited for some reason. 🤔

**Comment by josh-hemphill** [comment]
Actually I think it might be silently failing since the `.vite-ssg-temp` directory is getting created but not removed.

**Comment by josh-hemphill** [comment]
Finally tracked down and fixed the other unrelated issues.
Now if I await the `router.isReady()` it skips finishing installing the plugins and letting me alter the routes. It seems none of the `includedRoutes`, `onBeforePageRender`, or `onPageRendered` that I specified in `ssgOptions` are being run either...

**Comment by josh-hemphill** [comment]
It seems I can await `router.isReady()` in the hooks provided by `vite-ssg` but if I await it in the plugins, it fails silently.
I guess this was an issue of plugins loading before the router, creating an await loop where neither could continue?
For anyone else running into this, I go it working by doing:

```ts
export const install: UserModule = ({ app, router }) => {
	/* The solution was doing `router.isReady()` and then `then`ing it to
	detach it from the rest of the plugin loading as to not hold up 
	the router from loading in the first place */
	router.isReady().then(() => {
		const route = router.currentRoute.value;
		const lang = <string>route?.meta?.lang || 'en';
		const i18n = createI18n({
			legacy: false,
			locale: lang,
			messages,
		});

		app.use(i18n);
	});
};
```
