### ISSUE TITLE
SyntaxError: Unexpected token 'export'

### ISSUE THREAD

**Issue by vuejstime** [antfu/vite-ssg#140]
hello i have cloned vitesse project and then added `gsap` on it and very thing is fine unless i decided to build project
i have got this error
```
node_modules/gsap/ScrollToPlugin.js:127
export var ScrollToPlugin = {
^^^^^^

SyntaxError: Unexpected token 'export'
```
this link helped me to solve my problem
https://greensock.com/forums/topic/24799-syntaxerror-unexpected-token-export-on-npm-import/?do=findComment&comment=118873
i hope you check the problem

**Comment by antfu** [comment]
I guess `gsap` is aim to work client only? If so, you should use `<ClientOnly>` component to avoid including it in your SSG build.

**Comment by vuejstime** [comment]
no i just import it in my page and use it in mounted hook, it's not about the way i am using it's about the way i imported,
i have used it before for nuxt2 ssr and it was totally okay with that

**Comment by userquin** [comment]
@vuejstime add async callback on mount hook, use dynamic import to import the lib and remove the import: see the comment at top and the `install` method code here https://github.com/antfu/vite-ssg/issues/129#issuecomment-969149950
