### ISSUE TITLE
404 when reload the page

### ISSUE THREAD

**Issue by vuejstime** [antfu/vite-ssg#142]
hi 
when i deployed my project on an apache client, navigation is okay but when user refresh got 404.
i have tested nuxt2 ssg without any extra config and it's totally okay.
when i have used .htaccess file suggested by:
 https://router.vuejs.org/guide/essentials/history-mode.html#apache
 the problem was my dynamic slug routes did'nt get 404 error when slug is invalid.

**Comment by vuejstime** [comment]
i also added this to vite.config for generating my dynamic pages.
```
const includedRoutes = async (routes: string[]) => {
  const courses = await $fetch('course/index', { baseURL: BASE_URL, method: "get", headers: { Accept: 'application/json', 'Cache-Control': 'no-cache' } })
  let extraRoutes: string[] = []
  if (courses) {
    //@ts-ignore
    extraRoutes = courses.map(course => `/courses/${course.slug}`);
  }
  return [...routes.filter((i) => i !== '/courses/:slug'), ...extraRoutes];
}
```

**Comment by ziaadini** [comment]
it's my problem too

**Comment by antfu** [comment]
I think you will need to config index fallback and URL prettify in your server. It is probably not related to this package.

**Comment by vuejstime** [comment]
i found the problem it generate files in my root directory is there any config to generate directories?
`auth.html` to `auth directory with ->index.html`?

**Comment by vuejstime** [comment]
my problem solved by dirStyle: 'nested' option in vite.config file. i hope help someOne.
