### ISSUE TITLE
Importing `.mjs` dependency in `type: module` project causes `Error [ERR_REQUIRE_ESM]`

### ISSUE THREAD

**Issue by josh-hemphill** [antfu/vite-ssg#145]
Tring to use the alpha of Vuetify, and they have a dependency `vuetify/iconsets` which only has `.mjs` files.
I can also dynamic import it and get an error from esbuild complaining about top-level await.

I suppose Vuetify should really provide better export mapping, but if y'all would like to support `.mjs` imports in mjs projects, that would be nice.

**Comment by antfu** [comment]
Yes, vite-ssg currently works in CJS. PR welcome to migrate it to ESM if it got you interested :) Thanks.

**Comment by userquin** [comment]
closing this, should be fixed with latest version
