### ISSUE TITLE
Can I introduce router objects in ts files

### ISSUE THREAD

**Issue by nshusr** [antfu/vite-ssg#146]
App.vue
``` vue
<template>
  <button @click="toRoute('A')">
    router To A
  </button>
</template>

<script setup lang="ts">
import { toRoute } from '../utils/router'
</script>
```

that router how use

router.ts
``` ts
export function toRoute(name: string) {
  router // that router how use
}
```

**Comment by nshusr** [comment]
When using vite-ssg, the router object is introduced in the ts file,   https://github.com/hannoeru/vite-plugin-pages/issues/130

**Comment by techieoriname** [comment]
@nshusr that solution is for those using the plugin pages.
How about those not using it.

**Comment by nshusr** [comment]
> @nshusr that solution is for those using the plugin pages. How about those not using it.
https://github.com/hannoeru/vite-plugin-pages/issues/130#issuecomment-991933394

**Comment by techieoriname** [comment]
@nshusr that would work with the regular `vue` structure

But looking at something as shown below, the routes file only exports an array of routes.

`main.ts`
```typescript
import routes from "./routes"; // RouteRecordRaw[]

export const createApp = ViteSSG(
    App,
    {
        routes,
    },
    (ctx) => {}
)
```

`routes.ts`
```typescript
import type { RouteRecordRaw } from "vue-router";

export default <RouteRecordRaw[]>[
    {
        path: "/",
        component: () => import("./pages/Index.vue")
    }
]
```

**Comment by nshusr** [comment]
@techieoriname 
`main.ts`
``` ts
import routes from "./routes"; // RouteRecordRaw[]

export const createApp = ViteSSG(
    App,
    {
        routes,
    },
    (ctx) => {
      const { isClient, router, initialState } = ctx

      setRouter(router)
    }
)
```

`router.ts`
``` ts
```

**Comment by bekjon-me** [comment]
it is working, but when i try for the second time
