### ISSUE TITLE
Issue with catch-all routes with vite-plugin-pages

### ISSUE THREAD

**Issue by husayt** [antfu/vite-ssg#15]
Hi, @antfu 
thanks for great stuff you are producing. I wanted to give a try to vite-ssg and tried it within vitesse.

I managed to build the project with `vite-ssg build --script async`

But then why I try to test dist folder with `http-server` locally
I get this error:
[2021-02-09T19:07:30.754Z]  "GET /assets/[...all].45055fa7.js" Error (404): "Not found"

I guess this is smth to do with handling catch-all routes specifically. Maybe, the issue with `vite-plugin-pages` //cc @hannoeru

**Comment by hannoeru** [comment]
Can you provide a repro?

**Comment by hannoeru** [comment]
Try to clear site data at DevTools -> Application -> Storage, and re-register service worker.

**Comment by husayt** [comment]
I did update to latest vitesse and it works now. There were quite a few updates and latest works.

Thank you.
It is  all coming nicely together
