### ISSUE TITLE
Allow to set prettify indent size

### ISSUE THREAD

**Issue by NicolaSpadari** [antfu/vite-ssg#157]
Running `vite ssg` in order to render the app with this config:

```js
...
ssgOptions: {
    entry: "src/main.js",
    script: "async",
    formatting: "prettify", // Intendation is 2 spaces, no way to change it
    includedRoutes(routes) {
        ...
    },
    onPageRendered(route, html) {
        ...
    },
},
...
```

Looking into the sourcecode I see you use Prettier in order to format the HTML at https://github.com/antfu/vite-ssg/blob/main/src/node/build.ts#L243 but there is not tab width modifier.
The API allows you to specify the tab size https://prettier.io/docs/en/api.html#prettierresolveconfigfilepath--options

Can you add an optional field in the `ssgOptions` that allows us to override the 2 spaces with 4 or with tab?

**Comment by techieoriname** [comment]
I think you can simply create a `.prettierrc.json` and set your configuration example below;

```json
{
  "tabWidth": 4,
  "semi": true,
  "printWidth": 100,
  "endOfLine": "auto"
}
```

That works for me though.

**Comment by NicolaSpadari** [comment]
I already had prettier installed and configured to indent the lines by 4 spaces, but didn't work. Also tried adjust my settings like yours, but the ssg still renders it with 2 spaces
