### ISSUE TITLE
Vue-router Problem

### ISSUE THREAD

**Issue by kasec** [antfu/vite-ssg#16]
I'm building a project with this plugin and works pretty well, the problem is that vue-router doesn't resolve the right HTML, I thought that it was my configuration problem but watching *Vitesse* example I realize it works with the same resolution.

Build script create an SSG project but when put the directory in production or a http-server it renders its pages with JS(how spa), and not like a Static site.

I don't know if I'm misunderstanding something or if it's a real problem. I hope you can answer me and I don't make you uncomfortable.

**Comment by hannoeru** [comment]
SSG content is only served on the first request, then it will switch to SPA mode like a regular Vue SPA application.

If the content matched, Vue should only render the dynamic part of the page.

**Comment by antfu** [comment]
I think it's working as expected. Just like VuePress, only the initial request is handled by the SSG rendered HTML and then switch to SPA when the page gets fully loaded.
