### ISSUE TITLE
File ".js" extension is not being resolved

### ISSUE THREAD

**Issue by alexgrozav** [antfu/vite-ssg#161]
### The issue 
Code works during dev, but fails during SSG build. The culprit is the missing file extension when importing.

### Stacktrace
```
[vite-ssg] An internal error occurred.
[vite-ssg] Please report an issue, if none already exists: https://github.com/antfu/vite-ssg/issues
(node:54643) UnhandledPromiseRejectionWarning: Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/Users/alexgrozav/Workspace/inkline.io/node_modules/@inkline/inkline/components/IAlert/manifest' imported from /Users/alexgrozav/Workspace/inkline.io/.vite-ssg-temp/main.mjs
Did you mean to import @inkline/inkline/components/IAlert/manifest.js?
    at new NodeError (internal/errors.js:322:7)
    at finalizeResolution (internal/modules/esm/resolve.js:308:11)
    at moduleResolve (internal/modules/esm/resolve.js:731:10)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:842:11)
    at Loader.resolve (internal/modules/esm/loader.js:89:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:242:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:76:40)
    at link (internal/modules/esm/module_job.js:75:36)
```

This didn't happen in `0.16.2`.

**Comment by userquin** [comment]
@alexgrozav the new version `0.17.2` by default is `esm` (also supports `cjs`) while `0.16.2` is only `cjs`, so you should add the extension. You can try changing the format to  `cjs` on `ssgOptions` but there is a problem with the binary `vite-ssg` and maybe build will not work, I have fixed it on #160 (and a few other things):

![imagen](https://user-images.githubusercontent.com/6311119/147792020-8299c28f-d365-4232-9f39-5f0d392598cc.png)

**Comment by userquin** [comment]
@alexgrozav try with cjs format with the latest version released

**Comment by alexgrozav** [comment]
Thank you for the heads up! I'm updating the package to use `esm` properly.

**Comment by xibian1120** [comment]
how to solve it :  Unknown file extension ".vue"
