### ISSUE TITLE
Fresh install: pnpm build results in error

### ISSUE THREAD

**Issue by jjaimealeman** [antfu/vite-ssg#164]
Brand new fresh install.

I go to https://github.com/zynth17/vitailse and click "Use this Template" 
![](https://i.imgur.com/MoZuLGq.png)
And create a new repo from this template.

Git clone my new repo to local.

Run `pnpm i`.

Run `pnpm dev`, works fine! 👍

Run `pnpm build`, results in error. First appears fine: 
![](https://i.imgur.com/7MF10kK.png)

But finishes with error 
![](https://i.imgur.com/qb7ThUl.png)

**Comment by userquin** [comment]
you should file an issue on vitailse, shoukd update to latest version of `vite-ssg` it is using `0.17.1`

**Comment by userquin** [comment]
or just remove `vite-ssg` and add it again

**Comment by jjaimealeman** [comment]
> you should file an issue on vitailse

My apologies, didn't realize I was in the wrong place.

Heading there now 😖
https://github.com/zynth17/vitailse/issues
