### ISSUE TITLE
[question] ssg for social sharing not updated, and content is empty

### ISSUE THREAD

**Issue by u007** [antfu/vite-ssg#176]
hi,

my page/index.vue works with useHead on browser when script is executed,
but when called via curl, it showing the original title from Vitess not updated with my "Test Home"

```
<script lang="ts" setup>
import { useHead } from '@vueuse/head'

useHead({
  title: 'Test Home',
  meta: [
    {
      name: 'description',
      content: 'This is our home',
    },
  ],
})

```

result of curl

```
<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><link rel="icon" href="/favicon.ico"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Vitesse</title><script type="module" async="" crossorigin="" src="/assets/app.dc643c37.js"></script><link rel="modulepreload" href="/assets/vendor.b37b8568.js"><link rel="stylesheet" href="/assets/vendor.1f66886f.css"><link rel="stylesheet" href="/assets/app.015d4955.css"><link rel="manifest" href="/manifest.webmanifest"><meta name="description" content="Opinionated Vite Starter Template"><meta name="head:count" content="1"></head><body><div id="app" data-server-rendered="true"></div><script>window.__INITIAL_STATE__='{"pinia":{"alert":{"loading":false,"success":"","error":"","link":"","linkLabel":""}}}'</script></body></html>
```

**Comment by u007** [comment]
sorry i realise i could get the rendered versionafter npm run build and npm run preview. but i have a question, how do we prerender certain paths alike getstaticpaths in nextjs?

**Comment by bfourgeaud** [comment]
I have a similar problem.
I have opened a stackoverflow question regarding that [here](https://stackoverflow.com/questions/70745738/header-tags-not-updated-for-social-preview-cards).  

useHead works in the browser, the updated content is displayed.
But the socialpreview cards on facebook/twitter/... are not showing updated infos. Only the ones from the index page. As if the metatags were not server-side-rendered ... ?

Site hosted on Vercel.

**Example link : https://dev.energie-etre-ange.fr/services/soin-lahochi**
* On this link you can see that metadata seems to be correctly updated (title: Soin LaHoChi)
* If you check that link on https://socialsharepreview.com, you see that the metadata is not found ... (title: Energie de l'être ange)

The specific data is stored on pinia store, and prefeteched on server-side.

**ServerSide data retrival**
```js
import { createPinia } from 'pinia'
import { useRootStore } from '@/stores/root'

export const install = ({ app, router, initialState }) => {
  const pinia = createPinia()
  app.use(pinia)

  if (import.meta.env.SSR) {
    initialState.pinia = pinia.state.value
  } else {
    pinia.state.value = initialState.pinia || {}
  }

  router.beforeEach(async (to, from, next) => {
    const store = useRootStore(pinia)
    if (!store.ready)
      // perform the (user-implemented) store action to fill the store's state
      await store.initialize()
    next()
  })
}
```

**Pinia Store**
```js
import { defineStore, acceptHMRUpdate } from 'pinia'

// Import API Service
import { useAPI } from '@/services/api'
import Init from '@/queries/Init'

const api = useAPI()

export const useRootStore = defineStore({
  id: 'root',
  state: () => ({
    ready: false,
    categories: null,
    products: null,
    config: null
  }),

  getters: {},

  actions: {
    /**
     * Fetch all categories
     */
    async initialize() {
      const response = await api.fetch(Init)
      this.categories = response.categories || []
      this.products = response.products || []
      this.config = response.config || []
      this.ready = true
    }
  }
})
```

**Service page (where problem resides) - [slug].vue**
```html
<script setup>
  import { useRootStore } from '@/stores/root'
  import { useHead } from '@vueuse/head'

  const props = defineProps({ slug: String }) 
  const store = useRootStore()
  const service = computed(() => store.products.find(p => p.slug === props.slug))

  /* computed metaTags */
  useHead({
    title: service.value.name,
    meta: [
      { name: 'description', content: service.value.description },
      
      { property: 'og:type', content:'website' },
      { property: 'og:description', content: service.value.description },
      { property: 'og:title', content: service.value.name },
      { property: 'og:site_name', content: "Energie de l'être-ange" },
      { property: 'og:image', content: service.value.image.url },
      { property: 'og:url', content: `${import.meta.env.VITE_VERCEL_URL ? import.meta.env.VITE_VERCEL_URL : '' }/services/${service.value.slug}`},

      { name: 'twitter:title', content: service.value.name },
      { name: 'twitter:description', content:  service.value.description },
      { name: 'twitter:image', content:  service.value.image.url },
      { name: 'twitter:card', content: 'summary_large_image' },
    ]
  })
</script>
```

**Comment by DerYeger** [comment]
I have a similar problem. *All* of my pretended pages are empty.
See [this repository](https://github.com/DerYeger/jan-mueller/tree/next) for the issue.

All generated `*.html` files have a body that looks like the following snippet.
Nothing is being rendered.

```html
<body>
  <div id="app" class="font-sans text-primary"></div>
  <link rel="stylesheet" href="/assets/app.b076dedc.css">
</body>
```

**Comment by DerYeger** [comment]
> I have a similar problem. _All_ of my pretended pages are empty. See [this repository](https://github.com/DerYeger/jan-mueller/tree/next) for the issue.
> 
> All generated `*.html` files have a body that looks like the following snippet. Nothing is being rendered.
> 
> ```
> <body>
>   <div id="app" class="font-sans text-primary"></div>
>   <link rel="stylesheet" href="/assets/app.b076dedc.css">
> </body>
> ```

This was caused by the issue described in #118

**Comment by u007** [comment]
no my issue was something else. my page does have id="app" div

**Comment by u007** [comment]
anyone have a solutions? its been here for over a month now, urgently need this fix

**Comment by bfourgeaud** [comment]
@u007 I haven't found any simple solution to this problem so I switch my project to NextJS.
But The solution lies somewhere in vite-ssg confurguration and the "**includesRoutes**" options.

As a matter of fact, you have to tell vite-ssg what real routes are behind the dynamic route, and make an API call at build time to tell him what pages to generate. It ius the only way to server-side-generate the dynamic pages. On NextJS this handling is automatic and is widly known (GetStaticPaths), but on vite-ssg I couldn't find no example of it, and there is nothing in the documentation...

Here is another github issue where they are talking about that subject (related to vite-plugin-pages and dynamic route generation with vite-ssg) :
https://github.com/hannoeru/vite-plugin-pages/issues/40

Hoping for you o find your answer, I've searched for weeks without solutions.

**Comment by DerYeger** [comment]
> @u007 I haven't found any simple solution to this problem so I switch my project to NextJS. But The solution lies somewhere in vite-ssg confurguration and the "**includesRoutes**" options.
> 
> As a matter of fact, you have to tell vite-ssg what real routes are behind the dynamic route, and make an API call at build time to tell him what pages to generate. It ius the only way to server-side-generate the dynamic pages. On NextJS this handling is automatic and is widly known (GetStaticPaths), but on vite-ssg I couldn't find no example of it, and there is nothing in the documentation...
> 
> Here is another github issue where they are talking about that subject (related to vite-plugin-pages and dynamic route generation with vite-ssg) : [hannoeru/vite-plugin-pages#40](https://github.com/hannoeru/vite-plugin-pages/issues/40)
> 
> Hoping for you o find your answer, I've searched for weeks without solutions.

Yes, you have to configure the paths that are statically generated. [Vitesse has a neat shortcut](https://github.com/DerYeger/jan-mueller/blob/ef3b7f75fac8576a5d4afc8086cf0d1ee11bf532/src/main.ts#L3) for this.
Also, [dynamic routes have to be configured manually](https://github.com/DerYeger/jan-mueller/blob/ef3b7f75fac8576a5d4afc8086cf0d1ee11bf532/vite.config.ts#L198).

**Comment by u007** [comment]
okay i was testing on a bare empty vitesses repo and it works!
i found out was using **pinia-plugin-persistedstate** that messed up my ssg.

here is what i found, using computed helps with header that loads from data
```
useHead({
  title: computed<string>(() => product.value?.name ?? ''),
})

```
i added my custom route with data inside main.ts.
under pages/products/[id].vue, i use route.params.id to get the id and pass as prop "id" to components/products/view that actually does the loading of data.

so inside pages/products/[id].vue, i do not need to declare useHead here.


```
import Product from '~/components/products/view.vue'
//... existing code
const routes = setupLayouts([
  ...generatedRoutes,
  {
    name: 'products-id-xxxxx',
    path: '/products/xxxxx',
    component: Product,
    props: {
      id: 'xxxxx',
    },
    meta: {
      layout: 'default'
    }
  },
])

console.log('generatedroutes', generatedRoutes)
// https://github.com/antfu/vite-ssg
const viteApp = ViteSSG(
// ...
```

inside  '~/components/products/view.vue', i have to declare both onServerPrefetch and onMounted. serverprefetch does not seems to run on client side, so you will still need onMounted to have the data loading on client side (in nextjs, getstaticprops is passed to client side, but i can live with this)

```
const loadData = async () => {
  // do your ajax
  // product.value = result
}

onMounted(async() => {
  loading.value = true
  await loadData().finally(() => {
    loading.value = false
  })
  console.log('mounted')
})

onServerPrefetch(async () => {
  // component is rendered as part of the initial request
  // pre-fetch data on server as it is faster than on the client
  loading.value = true
  await loadData().finally(() => {
    loading.value = false
  })
  console.log('created', product.value)
})

useHead({
  title: computed<string>(() => product.value?.name ?? 'empty'),
})
```

**Comment by u007** [comment]
thank you @bfourgeaud for your direction :)
and thank you @DerYeger for your tips, it got to my solution.

**Comment by spokospace** [comment]
> okay i was testing on a bare empty vitesses repo and it works! i found out was using **pinia-plugin-persistedstate** that messed up my ssg.
> 
> here is what i found, using computed helps with header that loads from data
> 
> ```
> useHead({
>   title: computed<string>(() => product.value?.name ?? ''),
> })
> ```
> 
> i added my custom route with data inside main.ts. under pages/products/[id].vue, i use route.params.id to get the id and pass as prop "id" to components/products/view that actually does the loading of data.
> 
> so inside pages/products/[id].vue, i do not need to declare useHead here.
> 
> src/main.ts
> 
> ```
> import Product from '~/components/products/view.vue'
> //... existing code
> const routes = setupLayouts([
>   ...generatedRoutes,
>   {
>     name: 'products-id-xxxxx',
>     path: '/products/xxxxx',
>     component: Product,
>     props: {
>       id: 'xxxxx',
>     },
>     meta: {
>       layout: 'default'
>     }
>   },
> ])
> 
> console.log('generatedroutes', generatedRoutes)
> // https://github.com/antfu/vite-ssg
> const viteApp = ViteSSG(
> // ...
> ```
> 
> inside '~/components/products/view.vue', i have to declare both onServerPrefetch and onMounted. serverprefetch does not seems to run on client side, so you will still need onMounted to have the data loading on client side (in nextjs, getstaticprops is passed to client side, but i can live with this)
> 
> ```
> const loadData = async () => {
>   // do your ajax
>   // product.value = result
> }
> 
> onMounted(async() => {
>   loading.value = true
>   await loadData().finally(() => {
>     loading.value = false
>   })
>   console.log('mounted')
> })
> 
> onServerPrefetch(async () => {
>   // component is rendered as part of the initial request
>   // pre-fetch data on server as it is faster than on the client
>   loading.value = true
>   await loadData().finally(() => {
>     loading.value = false
>   })
>   console.log('created', product.value)
> })
> 
> useHead({
>   title: computed<string>(() => product.value?.name ?? 'empty'),
> })
> ```
> 
> and to fix pinia persisted state, inside modules/pinia
> 
> ```
> if (isClient) {
>   pinia.use(piniaPluginPersistedstate)
>   pinia.state.value = (initialState.pinia) || {}
> } else {
>   initialState.pinia = pinia.state.value
> }
> ```

Hello @u007, can u use $route.params with generatedRoutes with objects to dynamic pages?

I have issue after add custom routes to generatedRoutes, I used props in my objects, but then $route.params in template dont' work.

**Comment by jaxoncrosmas** [comment]
If anyone is coming here banging their head trying to figure out why ViteSSG is not creating head records in the generated static HTML files, you're not alone. I spent way too many hours figuring out why the records were not being generated for me.

DO NOT include `app.use(createHead())` in your main.ts/main.js file. ViteSSG will do this automatically. I made this mistake when migrating to ViteSSG. Once I removed this from my main.ts/main.js file, the records were showing in my generated static HTML files.

**Comment by u007** [comment]
thank you for sharing, thats good to know 🫡

**Comment by rebz** [comment]
> okay i was testing on a bare empty vitesses repo and it works! i found out was using **pinia-plugin-persistedstate** that messed up my ssg.
> 
> here is what i found, using computed helps with header that loads from data
> 
> ```
> useHead({
>   title: computed<string>(() => product.value?.name ?? ''),
> })
> ```
> 
> i added my custom route with data inside main.ts. under pages/products/[id].vue, i use route.params.id to get the id and pass as prop "id" to components/products/view that actually does the loading of data.
> 
> so inside pages/products/[id].vue, i do not need to declare useHead here.
> 
> src/main.ts
> 
> ```
> import Product from '~/components/products/view.vue'
> //... existing code
> const routes = setupLayouts([
>   ...generatedRoutes,
>   {
>     name: 'products-id-xxxxx',
>     path: '/products/xxxxx',
>     component: Product,
>     props: {
>       id: 'xxxxx',
>     },
>     meta: {
>       layout: 'default'
>     }
>   },
> ])
> 
> console.log('generatedroutes', generatedRoutes)
> // https://github.com/antfu/vite-ssg
> const viteApp = ViteSSG(
> // ...
> ```
> 
> inside '~/components/products/view.vue', i have to declare both onServerPrefetch and onMounted. serverprefetch does not seems to run on client side, so you will still need onMounted to have the data loading on client side (in nextjs, getstaticprops is passed to client side, but i can live with this)
> 
> ```
> const loadData = async () => {
>   // do your ajax
>   // product.value = result
> }
> 
> onMounted(async() => {
>   loading.value = true
>   await loadData().finally(() => {
>     loading.value = false
>   })
>   console.log('mounted')
> })
> 
> onServerPrefetch(async () => {
>   // component is rendered as part of the initial request
>   // pre-fetch data on server as it is faster than on the client
>   loading.value = true
>   await loadData().finally(() => {
>     loading.value = false
>   })
>   console.log('created', product.value)
> })
> 
> useHead({
>   title: computed<string>(() => product.value?.name ?? 'empty'),
> })
> ```
> 
> and to fix pinia persisted state, inside modules/pinia
> 
> ```
> if (isClient) {
>   pinia.use(piniaPluginPersistedstate)
>   pinia.state.value = (initialState.pinia) || {}
> } else {
>   initialState.pinia = pinia.state.value
> }
> ```

This post helped me solve my own SSR SEO issues with dynamic routes. Allowed me to circumvent working with `defineBasicLoader` or `defineColadaLoader`. Thank you.

I did slightly deviate. I was able to use `useHead` within both my `src/pages/parent.vue` and `src/pages/parent/[...id].vue` page.

If anyone else comes across this post... when using `useHead` I passed a computed property into it. Example below...

```
const router = useRouter();
const itemID = computed(() => router.currentRoute.value.params?.id)

const data = ref();
const loadData = async () => {
  data.value = await getItemByID(itemID.value)
};

watch(itemID, async () => {
  if (itemID.value) {
    await loadData()
  }
}, { immediate: true });

onServerPrefetch(async () => await loadData());

const seoHead = computed(() => ({
  title: data.value.title
});

useHead(seoHead);
```
