### ISSUE TITLE
Error with SSG after upgrade from 7.0 to 8.9

### ISSUE THREAD

**Issue by matt-rollinson** [antfu/vite-ssg#18]
Hey,

Thanks for making vite-ssg, it's pretty great!

However when I upgraded from 7.0 to 8.9 I'm getting an error (window not defined) when it builds for server, I dont recieve this error in 7.0 - I'm using vite version 2.0.1 and it still builds fine with 7.0.

I now get an error saying window is not defined. I can keep building in 7.0 but I'd like to use the includedRoutes feature pretty soon, have you got any suggestions please?

Also, it's a bit unrelated but I just wondered if you had any tips using vueuse/firebase in ssg? I keep getting an error about firebase-admin needing to be used for the server build?

Any help would be greatly appreciated!

Thanks again for vite-ssg!

**Comment by antfu** [comment]
Can you share a repro?

**Comment by matt-rollinson** [comment]
Thanks for the quick response!

Sure, I've just set up this repo and it has the same issue - https://github.com/matt-rollinson/vite-ssg-example - I've used <client-only> where I thought components needed to be on the client

Hope this helps to debug, if I can help in anyway, please let me know.

Thanks again :)

**Comment by antfu** [comment]
Looks more like a problem of Splide

![image](https://user-images.githubusercontent.com/11247099/108357701-bf611100-7228-11eb-9ac6-be612f97ab03.png)

It should check if window exists before using it.

**Comment by matt-rollinson** [comment]
Ah okay, I should have checked that, I thought as it worked in the past it might have been a vite issue, my apologies!

Even if it's an async component and loaded in <client-only> it'll still get used by the static site generator? I'm pretty new to ssg but thanks for helping :)
