### ISSUE TITLE
Unknown file extension ".css" with swiper 

### ISSUE THREAD

**Issue by leosin** [antfu/vite-ssg#191]
preview
https://stackblitz.com/edit/vitejs-vite-mpqpqd?file=src/App.vue

when i use vite-ssg plugin to build html

it return some error

```
(node:20) UnhandledPromiseRejectionWarning: TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".css" for /home/projects/vitejs-vite-mpqpqd/node_modules/swiper/swiper.min.css
```

**Comment by userquin** [comment]
uhmm, not a good example, but we can fix it: vite-ssg requires a lot of work, I have it working on local but will fail since you cannot mount the app on client side, preparing a vitesse repo with swiper on default layout.

**Comment by userquin** [comment]
> preview https://stackblitz.com/edit/vitejs-vite-mpqpqd?file=src/App.vue
> 
> when i use vite-ssg plugin to build html
> 
> it return some error
> 
> ```
> (node:20) UnhandledPromiseRejectionWarning: TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".css" for /home/projects/vitejs-vite-mpqpqd/node_modules/swiper/swiper.min.css
> ```

The trick is to add a plugin to load the css, here the repo https://github.com/userquin/vite-ssg-swiper:
1) change `import 'swiper/css'` to `import 'swiper.css'` ([import](https://github.com/userquin/vite-ssg-swiper/blob/main/src/layouts/default.vue#L2))
2) add vite plugin with `enforce: 'pre'` ([plugin](https://github.com/userquin/vite-ssg-swiper/blob/main/vite.config.ts#L30)):
```ts
    {
      name: 'fix-swipper-css',
      enforce: 'pre',
      resolveId(id) {
        if (id === 'swiper.css') return 'fix-swiper.css'
      },
      async load(id) {
        if (id === 'fix-swiper.css') {
          return await fs.readFile(
            './node_modules/swiper/swiper.min.css',
            'utf-8',
          )
        }
      },
    },
```

**Comment by userquin** [comment]
https://streamable.com/g904qv

**Comment by leosin** [comment]
great idea !!
💯  it works :)
thank you very much!!!!

i feedback to swiper author this Issues..........
And then _Closing as not related to Swiper_ hahaha 😭
