### ISSUE TITLE
Work with any UI ?

### ISSUE THREAD

**Issue by hunteryun** [antfu/vite-ssg#197]
I try naive-ui, and ant design, not work, there have any work UI?

也许这是一个愚蠢的问题，但是 我真的尽力研究了，我能找到的信息很少

**Comment by LuckLin520** [comment]
我想你是不是跟我一样的问题呢？
![image](https://user-images.githubusercontent.com/33896086/153988742-fc707fdb-5bea-42b4-b62d-5e255986252e.png)
确实我对这个问题不知道怎么解决？

**Comment by hunteryun** [comment]
yes, same issue, and I try many UI, all have some problem, so I'm confused, what's the point of existence if it can't work with UI? Are there other application scenarios?

**Comment by hunteryun** [comment]
我找到了这个：https://github.com/antfu/vite-ssg/issues/166， 也许这不是vite-ssg的问题，我只是希望能有一个可以配合工作的的

**Comment by LuckLin520** [comment]
根据你给的提示我找到了[#161 ](https://github.com/antfu/vite-ssg/issues/161)
添加了ssgOption后确实解决了问题可以成功执行build，但是我的vite.config.ts报错'ssgOptions' does not exist in type 'UserConfigExport'

**Comment by hunteryun** [comment]
恩，确实可以了，只是我还是放弃了，我是与后端集成，研究了很久，还有其他很多问题
