### ISSUE TITLE
Support for <title> and other meta tags

### ISSUE THREAD

**Issue by sibbng** [antfu/vite-ssg#2]
I just tried using it on [vitesse](https://github.com/antfu/vitesse) template with [useTitle](https://vueuse.js.org/?path=/story/browser--usetitle) function. The title changes didn't applied to `html` output. I have tried using [vue-composable](https://pikax.me/vue-composable/)'s [useTitle](https://pikax.me/vue-composable/composable/meta/title.html) function. but didn't work too.

Also tried using portals, no luck.
```html
<teleport to="head">
  <title>New Title</title>
</teleport>
```

**Comment by antfu** [comment]
Vue SSR only renders main component html, updating heads need to be handled specially in this plugin. I am still working on it. Looking for a good lib to updating the meta tags from a JS object (https://twitter.com/antfu7/status/1340971235618955265?s=20), if anyone knows any, please drop some links. Thanks.

**Comment by antfu** [comment]
Supported in v0.4.0 by the power of @vueuse/head
