### ISSUE TITLE
ReferenceError: window is not defined when importing progressive-image.js

### ISSUE THREAD

**Issue by mseele** [antfu/vite-ssg#21]
I want to add https://github.com/craigbuckler/progressive-image.js to my vite-ssg app and do this by adding

```
import 'progressive-image.js/dist/progressive-image.js'
import 'progressive-image.js/dist/progressive-image.css'
```

to the `main.ts`. On _Build for server..._ i get _ReferenceError: window is not defined_.
I used vitesse as base and know it's possible to create a module. But i cannot import the two resources in a isClient if clause.
Is there any way to import these resources only on client generation only?

**Comment by mseele** [comment]
I've created a demo repo https://github.com/mseele/vitesse-progressive-image.js. Commit https://github.com/mseele/vitesse-progressive-image.js/commit/d9e579d5a76327f706417831d172d9009ccd5578 shows my problem. How can i fix this? Thank you.

**Comment by falstack** [comment]
I have same issues

**Comment by zhxqc** [comment]
I have same issues

**Comment by 3nuc** [comment]
I get that there's no `window` in SSG but what's the escape hatch here?

I put the entire App.vue router-view in https://github.com/antfu/vite-ssg#clientonly tags but it doesn't budge.

**Comment by PatrikBird** [comment]
I have the same issue (ReferenceError: window is not defined) while playing around with p5.js sketches using vitesse. 
I'd like to exclude the component from SSG but wrapping the components in <client-only> doesn't work for me.

**Comment by userquin** [comment]
The problem here is that libraries that are not SSR/SSG aware should be loaded with `dynamic import`, for example, for `progressive-image`:
```js
 if (typeof window !== 'undefined') {
  import('progressive-image.js/dist/progressive-image.js')
 }
```
 or using `onMounted / beforeMount` hooks.

You can see an example on `src/modules/pwa.ts` module on `vitesse` template, where the `virtual:pwa-register` module (this guy will register the `service worker`) is loaded only if `isClient` is `true`.
