### ISSUE TITLE
An internal error occurred using includedRoutes option

### ISSUE THREAD

**Issue by rezelute** [antfu/vite-ssg#220]
I am using the Vitesse template and when I try to use the includedRoutes option in a very basic way, I am getting an Internal error:
```
ssgOptions: {
    script: 'async',
    formatting: 'minify',
    onFinished() { generateSitemap() },
    includedRoutes(paths, routes) {
      console.log('paths is >  ', paths)
      return paths; 
      // exclude all the route paths that contains 'foo'
      // return paths.filter(i => !i.includes('foo'))
    },
  },
```

The paths are:

```
[vite-ssg] Build for server...
vite v2.8.6 building SSR bundle for production...
✓ 24 modules transformed.
.vite-ssg-temp/manifest.webmanifest        0.38 KiB
.vite-ssg-temp/main.mjs                    23.17 KiB
.vite-ssg-temp/assets/style.83469b32.css   13.87 KiB
paths is >   [ '/about', '/food', '/', '/:all(.*)*', '/hi/:name' ]

[vite-ssg] An internal error occurred.
[vite-ssg] Please report an issue, if none already exists: https://github.com/antfu/vite-ssg/issues
(node:43200) UnhandledPromiseRejectionWarning: Error: [vite-ssg] Error on page: /:all(.*)*
Error: ENOENT: no such file or directory, open '...\TestGround\vitesse-1\dist\:all(.*)*.html'
```

**Comment by userquin** [comment]
@rezelute you should use `nuxt` notation since you're including all routes (also dynamic ones), so you cannot use `:` on a file name.

**Comment by rezelute** [comment]
Thank you for the reply, how do you mean "nuxt notation" sorry? In the original example given in the docs it just shows this:
```
export default {
  plugins: [],
  ssgOptions: {
    includedRoutes(paths, routes) {
      // exclude all the route paths that contains 'foo'
      return paths.filter(i => !i.includes('foo'))
    },
  },
}
```
Do you mean that in that example i should also be filtering out any file name with ":" as well as "foo" ?

**Comment by userquin** [comment]
@rezelute 

On `vite-plugin-pages` configuration:
- `routeStyle`: https://github.com/hannoeru/vite-plugin-pages#routestyle
- follow the link [Nuxtjs Routing](https://nuxtjs.org/docs/2.x/features/file-system-routing)

You can check also this entry, https://github.com/antfu/vitesse/discussions/169, search `Step one, include dynamic routes generation:`, you have the configuration and some honts there.

**Comment by userquin** [comment]
> Do you mean that in that example i should also be filtering out any file name with ":" as well as "foo" ?

You shoud rename the logic names using `:`, just replace them with `_`: on generation, the logic name will be used to generate the html files, and so the error, using `nuxt` style you will be able to generate the html files via `vite-ssg`.

**Comment by rezelute** [comment]
I think that makes sense, thank you, i will give this a try 👍
