### ISSUE TITLE
Cannot find module './jsdomGlobal'

### ISSUE THREAD

**Issue by mcasante** [antfu/vite-ssg#221]
Last week I've opened the PR #213 with an attempt to fix an error occurring on import of jsdomGlobal. Turns out I just introduced a new one 😅.
Using `_require` doesn't solve the problem. I think the other proposed solution may solve the problem, but once I couldnt test it properly locally, I've decided do open this issue instead of submitting another PR.

**Comment by josh-hemphill** [comment]
I tried updating my ESM project, hoping the recent jsdomGlobal update would fix things for some libraries that weren't playing well with SSG, and it seems to fail silently now. I don't get errors until plugins try accessing browser globals.

**Comment by userquin** [comment]
@mcasante can you test your repo with https://github.com/antfu/vite-ssg/issues/150#issuecomment-1113992002?
