### ISSUE TITLE
How to specify vite config file? -c flag like in vite CLI?

### ISSUE THREAD

**Issue by tobidalhof** [antfu/vite-ssg#236]
Is this possible? I have a project with multiple vite config files.

Example: `vite-ssg build -c vite.config.website.ts`

**Comment by BinaryBen** [comment]
Just to confirm, is this currently not possible?

**Comment by antfu** [comment]
PR welcome

**Comment by LouisMazel** [comment]
For guys coming here, use `-c` or `--config`

Ex:

```bash
vite build -c build/vite.config.ts
```
