### ISSUE TITLE
"window is not defined" with vue-router

### ISSUE THREAD

**Issue by evdevru** [antfu/vite-ssg#253]
How to fix it ? "vue-router": "^4.0.15"

`.vite-ssg-temp/main.mjs                    476.33 KiB
.vite-ssg-temp/assets/style.b3155112.css   55.31 KiB

[vite-ssg] An internal error occurred.
[vite-ssg] Please report an issue, if none already exists: https://github.com/antfu/vite-ssg/issues
C:\Users\sonic\Documents\csgo-dark-dashboard\node_modules\vue-router\dist\vue-router.cjs.js:505      
    const { history, location } = window;
                                  ^

ReferenceError: window is not defined
    at useHistoryStateNavigation (C:\Users\sonic\Documents\csgo-dark-dashboard\node_modules\vue-router\dist\vue-router.cjs.js:505:35)
    at createWebHistory (C:\Users\sonic\Documents\csgo-dark-dashboard\node_modules\vue-router\dist\vue-router.cjs.js:597:31)
    at file:///C:/Users/sonic/Documents/csgo-dark-dashboard/.vite-ssg-temp/main.mjs:1625:14
    at ModuleJob.run (node:internal/modules/esm/module_job:195:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:337:24)
    at async build (file:///C:/Users/sonic/Documents/csgo-dark-dashboard/node_modules/vite-ssg/dist/chunks/build.mjs:167:87)
    at async Object.handler (file:///C:/Users/sonic/Documents/csgo-dark-dashboard/node_modules/vite-ssg/dist/node/cli.mjs:20:3)`

**Comment by the-illarionov** [comment]
@evdevru how you dealed with that problem?

**Comment by Bernankez** [comment]
> @evdevru how you dealed with that problem?

Did you have an unused `router` in your project? I have an unused exported router in my `routes/index`, and it causes the problem.

**Comment by Alioth996** [comment]
I have a some problem:

> Please report an issue, if none already exists: https://github.com/antfu/vite-ssg/issues
file:///X:/2023-PItem/txt-reader/node_modules/.pnpm/vue-router@4.1.6_vue@3.2.47/node_modules/vue-router/dist/vue-router.mjs:708
    base = location.host ? base || location.pathname + location.search : '';
    ^
ReferenceError: location is not defined
    at createWebHashHistory (file:///X:/2023-PItem/txt-reader/node_modules/.pnpm/vue-router@4.1.6_vue@3.2.47/node_modules/vue-router/dist/vue-router.mjs:708:5)
    at file:///X:/2023-PItem/txt-reader/.vite-ssg-temp/main.mjs:68:12
    at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:385:24)
    at async build (file:///X:/2023-PItem/txt-reader/node_modules/.pnpm/vite-ssg@0.22.1_r2d4zfya2kg425tu5u6xyulg6i/node_modules/vite-ssg/dist/shared/vite-ssg.62550b28.mjs:996:87)
    at async Object.handler (file:///X:/2023-PItem/txt-reader/node_modules/.pnpm/vite-ssg@0.22.1_r2d4zfya2kg425tu5u6xyulg6i/node_modules/vite-ssg/dist/node/cli.mjs:29:5)
###

**Comment by Alioth996** [comment]
> I have a same problem:
> 
> > Please report an issue, if none already exists: https://github.com/antfu/vite-ssg/issues
> > file:///X:/2023-PItem/txt-reader/node_modules/.pnpm/vue-router@4.1.6_vue@3.2.47/node_modules/vue-router/dist/vue-router.mjs:708
> > base = location.host ? base || location.pathname + location.search : '';
> > ^
> > ReferenceError: location is not defined
> > at createWebHashHistory (file:///X:/2023-PItem/txt-reader/node_modules/.pnpm/vue-router@4.1.6_vue@3.2.47/node_modules/vue-router/dist/vue-router.mjs:708:5)
> > at file:///X:/2023-PItem/txt-reader/.vite-ssg-temp/main.mjs:68:12
> > at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
> > at async Promise.all (index 0)
> > at async ESMLoader.import (node:internal/modules/esm/loader:385:24)
> > at async build (file:///X:/2023-PItem/txt-reader/node_modules/.pnpm/[vite-ssg@0.22.1_r2d4zfya2kg425tu5u6xyulg6i](mailto:vite-ssg@0.22.1_r2d4zfya2kg425tu5u6xyulg6i)/node_modules/vite-ssg/dist/shared/vite-ssg.62550b28.mjs:996:87)
> > at async Object.handler (file:///X:/2023-PItem/txt-reader/node_modules/.pnpm/[vite-ssg@0.22.1_r2d4zfya2kg425tu5u6xyulg6i](mailto:vite-ssg@0.22.1_r2d4zfya2kg425tu5u6xyulg6i)/node_modules/vite-ssg/dist/node/cli.mjs:29:5)

### I import ``routes`` from ``src/router/index.ts`` :

![image](https://user-images.githubusercontent.com/64628135/225079278-fb2ca1f0-c947-4420-9d97-a5c7ceefb7e1.png)

### ``router/index.ts``
```js
import { createWebHashHistory, createRouter, RouteRecordRaw } from 'vue-router'

import Home from '@/views/Home/index.vue'

const routes: RouteRecordRaw[] = [
  {
    path: '/',
    redirect: '/home'
  },
  {
    path: '/home',
    name: 'Home',
    meta: {
      title: '文曲阅读_导入本地小说_支持离线阅读 支持txt格式'
    },
    component: Home
  },
  {
    path: '/reader/:bookName/:bookId',
    name: 'reader',
    meta: {
      title: '文曲阅读-阅读小说'
    },
    component: () => import('@/views/Reader/index.vue')
  },
  {
    path: '/setting',
    name: 'Setting',
    meta: {
      title: '文曲阅读-系统设置'
    },
    component: () => import('@/views/Option/index.vue')
  },
  {
    path: '/:pathMatch(.*)*', // 注意此处 404页面匹配规则和以前不相同，得采用这种配置方式才行
    name: '404',
    meta: {
      title: '404-访问路径不存在'
    },
    component: () => import('@/views/404.vue')
  }
]

const router = createRouter({
  history: createWebHashHistory(),
  routes
})

router.beforeEach((to, from) => {
  document.title = to.meta.title as string
})

export { routes }

export default router

```
### but when  ``routes`` define in ``main.ts``  , ``build`` is ok:

![image](https://user-images.githubusercontent.com/64628135/225080522-507d4034-3327-48f1-9aab-92f6c6a1c394.png)

**Comment by JeffreyArts** [comment]
As an addition, also remove the history option as [described in this issue](https://github.com/antfu/vite-ssg/issues/20)


```
import { createWebHistory } from "vue-router"
const routerOptions = {
  routes,
  history: createWebHistory()
}
```

**Should become**
```
const routerOptions = {
  routes,
}
```
