### ISSUE TITLE
How to set import.meta.env.BASE_URL, like vite-ssr in viteSSR(App, {routers, base: ({url})=>{}})?

### ISSUE THREAD

**Issue by JerrySir** [antfu/vite-ssg#264]
i want to set i18n router, how to set this router locations, thanks.

**Comment by JerrySir** [comment]
I want to set the localization path. How can I do this?
www.test.com => www.test.com/ko/
thank you very much indeed

**Comment by tim-kilian** [comment]
How did you solved this ?

**Comment by tim-kilian** [comment]
Ah, for me it was simply using import meta env BASE_URL

```
export const createApp = ViteSSG(App, { routes, base: import.meta.env.BASE_URL });
```
