### ISSUE TITLE
Vite 3 support

### ISSUE THREAD

**Issue by TheHunterDog** [antfu/vite-ssg#271]
### Clear and concise description of the problem

Support for the current version of vite.

### Suggested solution

Update packages.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
We do already
https://github.com/antfu/vite-ssg/blob/main/package.json#L86
