### ISSUE TITLE
Typescript type error for ssgOptions in vite.config.ts 

### ISSUE THREAD

**Issue by rezelute** [antfu/vite-ssg#279]
### Describe the bug

I get this type error (even though build works) in the `vite.config.ts` file.
![image](https://user-images.githubusercontent.com/13378850/183515367-ba083a08-bad5-4d35-b1da-4970ce1ed206.png)

Argument of type '{ server: { port: number; }; plugins: (Plugin_2 | Plugin | Plugin_2[])[]; resolve: { alias: { "@/": string; }; }; build: {}; ssgOptions: { script: string; onFinished(): void; }; }' is not assignable to parameter of type 'UserConfigExport'.
  Object literal may only specify known properties, and 'ssgOptions' does not exist in type 'UserConfigExport'.ts(2345)

Do you know how I resolve this?

Relevant packages:
"vite-ssg": "^0.20.2",
"vite-ssg-sitemap": "^0.3.2",
"vue": "^3.2.31",

### Reproduction

use ssgOptions in vite.config.ts

### System Info

```Shell
System:
    OS: Windows 10 10.0.19044
    CPU: (12) x64 AMD Ryzen 5 5600X 6-Core Processor
    Memory: 15.68 GB / 31.92 GB
  Binaries:
    Node: 14.20.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.5.4 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (103.0.1264.77)
    Internet Explorer: 11.0.19041.1566
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by TiemenSch** [comment]
I can get the error to disappear by importing anything (or even nothing ``{}``) from "vite-ssg".
An easy workaround is to do this:
```typescript
import { ViteSSGOptions } from "vite-ssg"
const ssgOptions: ViteSSGOptions = {
  script: "async",
  formatting: "minify",
  onFinished() {
    generateSitemap()
  },
}

export default defineConfig({
  ...,
  ssgOptions
})
``` 
Which at least uses the thing you import.

**Comment by antfu** [comment]
Could also prepend this to the config file:

```ts
/// <reference types="vite-ssg" />
```

**Comment by TiemenSch** [comment]
You learn something new everyday :)!

**Comment by rezelute** [comment]
Brilliant thanks Anthony 🎉
