### ISSUE TITLE
unable to resolve dependency tree

### ISSUE THREAD

**Issue by rainmanhhh** [antfu/vite-ssg#28]
`npm i -D vite-ssg`

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: undefined@undefined
npm ERR! Found: @vueuse/head@0.5.1
npm ERR! node_modules/@vueuse/head
npm ERR!   @vueuse/head@"^0.5.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @vueuse/head@"^0.3.1" from vite-ssg@0.8.12
npm ERR! node_modules/vite-ssg
npm ERR!   dev vite-ssg@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Comment by hannoeru** [comment]
Fixed in v0.9.0
