### ISSUE TITLE
Build error when using old js library

### ISSUE THREAD

**Issue by socketbear** [antfu/vite-ssg#284]
### Describe the bug

I'm a small developer who is obsessed with vite ssg. (sorry, bad english)

The old js lib worked well in the `pnpm dev` environment, but when I try to build it, an error occurs.
```
file:///Users/socketbear/Workspace/BoardGame-Helper/.vite-ssg-temp/main.mjs:1529
  origin: location.origin,
          ^

ReferenceError: location is not defined
    at file:///Users/socketbear/Workspace/BoardGame-Helper/.vite-ssg-temp/main.mjs:1529:11
    at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:385:24)
    at async build (file:///Users/socketbear/Workspace/BoardGame-Helper/node_modules/.pnpm/vite-ssg@0.20.2_k7shjfzctjeydlate74macei7a/node_modules/vite-ssg/dist/chunks/build.mjs:171:87)
    at async Object.handler (file:///Users/socketbear/Workspace/BoardGame-Helper/node_modules/.pnpm/vite-ssg@0.20.2_k7shjfzctjeydlate74macei7a/node_modules/vite-ssg/dist/node/cli.mjs:20: 3)
ELIFECYCLE  Command failed with exit code 1.
```

This is the contents of the corresponding `main.mjs` location.
## main.mjs
```
const defaultOptions$3 = {
  id: `dice-canvas-${Date.now()}`,
  enableShadows: true,
  shadowTransparency: 0.8,
  lightIntensity: 1,
  delay: 10,
  scale: 5,
  theme: "default",
  themeColor: "#2e8555",
  offscreen: true,
  assetPath: "/assets/dice-box/",
  origin: location.origin,
  meshFile: `models/default.json`,
  suspendSimulation: false
};
```

As a first attempt, I configured it to use a component through `clientOnly`, but the same error was output.
As a second attempt, I grabbed the `isClient` setting in the plugin and configured it to be used within `clientOnly`, but the same error was output.

No matter how much I changed, the created `main.mjs` was the same as above. No matter how you configure it, using `import` it seems to be configured as above. I really want the build output to work only in the `clientOnly` situation... What should I do?

### Reproduction

https://github.com/socketbear/BoardGame-Helper/tree/1-fix-build-issue

### System Info

```Shell
System:
    OS: macOS 12.5.1
    CPU: (8) arm64 Apple M1
    Memory: 75.45 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.16.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.11.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 104.0.5112.101
    Safari: 15.6.1
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
You should use dynamic imports with conditional client checks. This is not an issue of vite-ssg.
