### ISSUE TITLE
Custom directive support

### ISSUE THREAD

**Issue by Bluskript** [antfu/vite-ssg#29]
How would I support making a directive client-side-only? I like how much this library simplifies things, but I'm not really sure how to get something like `v-t` working. Currently trying to use it results in `SyntaxError: Custom directive is missing corresponding SSR transform and will be ignored.` [There are docs about how to fix this](https://github.com/intlify/vue-i18n-extensions#server-side-rendering-for-v-t-custom-directive), but they don't really make sense in the context of `vite-ssg`

[Related issue](https://github.com/vuejs/vitepress/issues/92)

**Comment by antfu** [comment]
Try this https://github.com/vueuse/patch-vue-directive-ssr

**Comment by Bluskript** [comment]
That worked, thank you!
