### ISSUE TITLE
SyntaxError: Named export 'forOwn' not found. The requested module 'lodash' is a CommonJS module

### ISSUE THREAD

**Issue by alex-galey** [antfu/vite-ssg#294]
### Describe the bug

Getting this error while lodash seems to come from vite-ssg  :

```
import { isPlainObject, forOwn, isArray, isString } from "lodash";
                        ^^^^^^
SyntaxError: Named export 'forOwn' not found. The requested module 'lodash' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'lodash';
const { isPlainObject, forOwn, isArray, isString } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:128:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:194:5)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:385:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:437:15)
    at async Object.build (/home/alex/Documents/AA-Matchers/Dev-Site/site/node_modules/vite-ssg/dist/chunks/build.cjs:171:87)
    at async Object.handler (/home/alex/Documents/AA-Matchers/Dev-Site/site/node_modules/vite-ssg/dist/node/cli.cjs:25:3)
error Command failed with exit code 1.
```

I was able to solve another similar issue with another dependency for an import I was "controlling"

Here is my config : 
```
  ssgOptions: {
    script: 'async',
    formatting: process.env.NODE_ENV === 'no-minify' ? 'prettify' : 'minify'
  }
```

and my project requires : "lodash": "4.17.21"

I tried with latest and 0.19.2, vite is 2.9.15

### Reproduction

"build": "cross-env NODE_ENV=production vite-ssg build"

### System Info

```Shell
System:
    OS: Linux 4.19 Debian GNU/Linux 10 (buster) 10 (buster)
    CPU: (2) x64 Intel(R) Core(TM)2 Duo CPU     P8400  @ 2.26GHz
    Memory: 2.48 GB / 7.54 GB
    Container: Yes
    Shell: 5.0.3 - /bin/bash
  Binaries:
    Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.16.0/bin/yarn
    npm: 8.16.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
  Browsers:
    Firefox: 103.0.1
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by mrhammadasif** [comment]
You have to use `lodash-es` library, lodash doesn't provides es modules

**Comment by alex-galey** [comment]
Thanks it worked !
I am facing other ESM compatibility-related issues till vite-ssg upgrade but I am closing this one.
