### ISSUE TITLE
Is it safe to update to peer @vueuse/head v0.8.x?

### ISSUE THREAD

**Issue by oberocks** [antfu/vite-ssg#295]
Hi awesome people,

Hey I was doing some weekend deps gardening, and hit a hitch with the update semver peer dep for [@vueuse/head](https://github.com/vueuse/head). The line is referenced below:

https://github.com/antfu/vite-ssg/blob/9fe4232a2eea3237c603e492a6e7e5da734b9c10/package.json#L86

Is it a breaker to change the peer specificity to this:

```json
"@vueuse/head": "^0.5.0 || ^0.6.0 || ^0.7.0 || ^0.8.0",
```
Here's a link to the @vueuse/head changes:
https://github.com/vueuse/head/releases/tag/v0.8.0

Cheers and thank you for the excellent package! And let me know if you just want me to push a PR through to you all!

**Comment by antfu** [comment]
Bumpped.

**Comment by oberocks** [comment]
@antfu you rock and thank you! 🍻
