### ISSUE TITLE
Unmet peer dependencies

### ISSUE THREAD

**Issue by ansidev** [antfu/vite-ssg#298]
### Describe the bug

```
ERR_PNPM_PEER_DEP_ISSUES  Unmet peer dependencies

.
└─┬ vite-ssg 0.21.0
  └── ✕ unmet peer @vueuse/head@"^0.5.0 || ^0.6.0 || ^0.7.0": found 0.8.2
```

This line should be updated: https://github.com/antfu/vite-ssg/blob/590580488475cdee5454799373087105449b13c1/package.json#L86

### Reproduction

https://github.com/ansidev/blog/pull/87

### System Info

```Shell
.
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by compilekaiten** [comment]
Should be updated for @vueuse/head 0.9.X release as well.

```
 WARN  Issues with peer dependencies found
.
└─┬ vite-ssg 0.21.0
  └── ✕ unmet peer @vueuse/head@"^0.5.0 || ^0.6.0 || ^0.7.0": found 0.9.4
  ```

**Comment by rezelute** [comment]
Same problem after updating to the latest version 😬
