### ISSUE TITLE
React Support

### ISSUE THREAD

**Issue by jonstuebe** [antfu/vite-ssg#30]
Is the plan for this plugin to remain `vue` specific? I'd love to have the same support with `react` if possible. But I also know that it's probably a lot of work and if that's not what your direction is for this plugin, I completely understand.

**Comment by antfu** [comment]
This plugin was written then Vite is still 1.0-rc and being Vue specific, so sorry for the name might be misleading.

While I would love to say I am happy to have it framework-agnostic, I am afraid that even someone finds a way to contribute to this project via a PR, I will not be able to maintain it.

So, as for now, maybe it's better to keep it vue specify, and for someone who knows react better to create/maintain a separate plugin.

Thanks for bringing this up.
