### ISSUE TITLE
Make the Head by useHead static as well

### ISSUE THREAD

**Issue by kecrily** [antfu/vite-ssg#305]
### Clear and concise description of the problem

Currently, if you use `useHead()` to define the title and meta tags, they are still dynamically after SSG.

### Suggested solution

Make the contents of useHead() static like the rest of the section.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by yswnldy** [comment]
from @vueuse/head v0.9.1 to the latest version, manage the document-head in vite-ssg build is not working.

@vueuse/head v0.9.0、v0.8.2、v0.7.13 is working.

you can try lower version.

**Comment by AxyLm** [comment]
+1
