### ISSUE TITLE
[question]: how can i use @intlify/vite-plugin-vue-i18n/messages

### ISSUE THREAD

**Issue by nandordudas** [antfu/vite-ssg#32]
I read the documentation of vite i18n plugin and found [a possible simpler solution](https://github.com/intlify/vite-plugin-vue-i18n#static-bundle-importing).
**The existing works fine i dont have any problems with it**.

I cannot build with ssg after i made change: `Error: Cannot find module '@intlify/vite-plugin-vue-i18n/messages'`

![image](https://user-images.githubusercontent.com/15153245/112760663-1dd39900-8ff8-11eb-9ab6-2d5fc4075e95.png)

Can is use this import with vite-ssg or not?

Thank you in advance for your answer

**Comment by hannoeru** [comment]
That is because it include it's own package name in virtual module,
in ssr mode vite will resolve that path to `node_module/@intlify/vite-plugin-vue-i18n`, so it won't find any file.
Just don't include package name in virtual module, then it will resolved correctly.
/cc @kazupon

**Comment by nandordudas** [comment]
Appendix: this example is coming from [vitesse - src/modules/i18n.ts:6](https://github.com/antfu/vitesse/blob/b7824239a8ab4542d3e2dc82fdcf98e70bec5fe2/src/modules/i18n.ts#L6).

Thanks for your help!
