### ISSUE TITLE
loading page is empty when setting base params in vite.config.ts

### ISSUE THREAD

**Issue by wookelvin** [antfu/vite-ssg#320]
### Describe the bug

When you set the 'base' param in vite.config.ts to specify a base path different from '/', the build output will generate the html correctly, however, when loading in the browser, the `<div id="app"></div>` contents will end up being empty. why?

### Reproduction

npm run build

### System Info

```Shell
System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
    Memory: 3.83 GB / 15.69 GB
  Binaries:
    Node: 16.17.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.18 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (107.0.1418.56)
    Internet Explorer: 11.0.19041.1566
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by wookelvin** [comment]
Apologies. Found the answer. I need to specify the base in the routerOptions when calling ViteSSG initially: 
`export const createApp = ViteSSG(
    App, 
    { 
        routes, 
        base: import.meta.env.BASE_URL ?? '/'
    }
);
`

**Comment by yassernasc** [comment]
Hi @wookelvin, do you have a working sample of your solution? maybe an open-source project.

Thanks.
