### ISSUE TITLE
升级到 vite 4 后, 打包代码后会有两份 css

### ISSUE THREAD

**Issue by Zhang-Wei-666** [antfu/vite-ssg#322]
### Describe the bug

1. 升级 vite 至 v4 版本
![image](https://user-images.githubusercontent.com/37876877/206954408-6c5e63a2-0b4b-4ec2-90e1-b7d0363ba434.png)

2. 构建代码后查看 index.html 文件
![image](https://user-images.githubusercontent.com/37876877/206954512-0b35fa2e-41f0-443b-a560-bd8b3d22300f.png)

### Reproduction

https://github.com/antfu/vite-ssg/tree/main/examples/multiple-pages

### System Info

```Shell
System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
    Memory: 16.94 GB / 31.96 GB
  Binaries:
    Node: 16.18.0 - D:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.19.2 - D:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (108.0.1462.46)
    Internet Explorer: 11.0.19041.1566
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by limer2** [comment]
@Zhang-Wei-666 请教下，您后面是怎么处理解决这个问题的？

**Comment by Zhang-Wei-666** [comment]
@limer2 配置了 critters 生成样式的规则, 使用了 ["swap"](https://github.com/GoogleChromeLabs/critters#preloadstrategy) 模式

```js
ssgOptions: {
  ...,
  crittersOptions: {
    inlineFonts: false,
    preloadFonts: false,
    preload: 'swap',
  },
  ...,
}
```

![image](https://github.com/antfu/vite-ssg/assets/37876877/4d1f1a26-e52d-4e3e-9587-ed2cde4a392c)

**Comment by limer2** [comment]
> @limer2 配置了 critters 生成样式的规则, 使用了 ["swap"](https://github.com/GoogleChromeLabs/critters#preloadstrategy) 模式
> 
> ```js
> ssgOptions: {
>   ...,
>   crittersOptions: {
>     inlineFonts: false,
>     preloadFonts: false,
>     preload: 'swap',
>   },
>   ...,
> }
> ```
> 
> ![image](https://user-images.githubusercontent.com/37876877/249313650-4d1f1a26-e52d-4e3e-9587-ed2cde4a392c.png)
> 
> 最终效果:
> 
> ```
> <link rel="preload" href="/assets/index-0433279b.css" as="style" onload="this.rel='stylesheet'">
> ```

@Zhang-Wei-666 非常感谢。我配置成preload: 'media'解决了。

**Comment by Zhang-Wei-666** [comment]
> @Zhang-Wei-666 非常感谢。我配置成preload: 'media'解决了。

@limer2  可以的, 选择合适自己的模式就行了 👍
