### ISSUE TITLE
Problems with file version reading

### ISSUE THREAD

**Issue by xywc-s** [antfu/vite-ssg#33]
I built a static site with vite-ssg, but when I updated a version, I found that the site couldn't read the new version of the file because it still read the old resources.

By tracing the browser load entry, I found that the file was read from inside the serverworker cache.

Is this a problem with the build process, and what should I do to get the browser to automatically load the latest version of the file?

![1](https://pic.rmb.bdstatic.com/bjh/5364787e6f20d4df92e442605d41d3d6.png)

![2](https://pic.rmb.bdstatic.com/bjh/3e3e597fc632fadb753524f23f49af6b.png)

**Comment by antfu** [comment]
See https://github.com/antfu/vite-plugin-pwa#automatic-reload-when-new-content-available

Close as it's not related to this project
