### ISSUE TITLE
location is not defined

### ISSUE THREAD

**Issue by Alioth996** [antfu/vite-ssg#336]
### Describe the bug

> > I have a same problem:
> > > Please report an issue, if none already exists: https://github.com/antfu/vite-ssg/issues
> > > file:///X:/2023-PItem/txt-reader/node_modules/.pnpm/vue-router@4.1.6_vue@3.2.47/node_modules/vue-router/dist/vue-router.mjs:708
> > > base = location.host ? base || location.pathname + location.search : '';
> > > ^
> > > ReferenceError: location is not defined
> > > at createWebHashHistory (file:///X:/2023-PItem/txt-reader/node_modules/.pnpm/vue-router@4.1.6_vue@3.2.47/node_modules/vue-router/dist/vue-router.mjs:708:5)
> > > at file:///X:/2023-PItem/txt-reader/.vite-ssg-temp/main.mjs:68:12
> > > at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
> > > at async Promise.all (index 0)
> > > at async ESMLoader.import (node:internal/modules/esm/loader:385:24)
> > > at async build (file:///X:/2023-PItem/txt-reader/node_modules/.pnpm/[vite-ssg@0.22.1_r2d4zfya2kg425tu5u6xyulg6i](mailto:vite-ssg@0.22.1_r2d4zfya2kg425tu5u6xyulg6i)/node_modules/vite-ssg/dist/shared/vite-ssg.62550b28.mjs:996:87)
> > > at async Object.handler (file:///X:/2023-PItem/txt-reader/node_modules/.pnpm/[vite-ssg@0.22.1_r2d4zfya2kg425tu5u6xyulg6i](mailto:vite-ssg@0.22.1_r2d4zfya2kg425tu5u6xyulg6i)/node_modules/vite-ssg/dist/node/cli.mjs:29:5)
> 
> ### I import `routes` from `src/router/index.ts` :
> ![image](https://user-images.githubusercontent.com/64628135/225079278-fb2ca1f0-c947-4420-9d97-a5c7ceefb7e1.png)
> 
> ### `router/index.ts`
> ```js
> import { createWebHashHistory, createRouter, RouteRecordRaw } from 'vue-router'
> 
> import Home from '@/views/Home/index.vue'
> 
> const routes: RouteRecordRaw[] = [
>   {
>     path: '/',
>     redirect: '/home'
>   },
>   {
>     path: '/home',
>     name: 'Home',
>     meta: {
>       title: '文曲阅读_导入本地小说_支持离线阅读 支持txt格式'
>     },
>     component: Home
>   },
>   {
>     path: '/reader/:bookName/:bookId',
>     name: 'reader',
>     meta: {
>       title: '文曲阅读-阅读小说'
>     },
>     component: () => import('@/views/Reader/index.vue')
>   },
>   {
>     path: '/setting',
>     name: 'Setting',
>     meta: {
>       title: '文曲阅读-系统设置'
>     },
>     component: () => import('@/views/Option/index.vue')
>   },
>   {
>     path: '/:pathMatch(.*)*', // 注意此处 404页面匹配规则和以前不相同，得采用这种配置方式才行
>     name: '404',
>     meta: {
>       title: '404-访问路径不存在'
>     },
>     component: () => import('@/views/404.vue')
>   }
> ]
> 
> const router = createRouter({
>   history: createWebHashHistory(),
>   routes
> })
> 
> router.beforeEach((to, from) => {
>   document.title = to.meta.title as string
> })
> 
> export { routes }
> 
> export default router
> ```
> 
> ### but when `routes` define in `main.ts` , `build` is ok:
> ![image](https://user-images.githubusercontent.com/64628135/225080522-507d4034-3327-48f1-9aab-92f6c6a1c394.png)

### Reproduction

use vite-ssg build but no work

### System Info

```Shell
System:
    OS: Windows 10 10.0.22000
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12700H
    Memory: 7.83 GB / 15.63 GB
  Binaries:
    Node: 16.15.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (110.0.1587.69), ChromiumDev (111.0.1661.41)
    Internet Explorer: 11.0.22000.120
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
It's how SSG works

**Comment by Alioth996** [comment]
> It's how SSG works

i get it,thinks!
