### ISSUE TITLE
source maps are generated, but they have a slight offset.

### ISSUE THREAD

**Issue by OrbisK** [antfu/vite-ssg#342]
### Describe the bug

*vite.config.ts*
```ts
{
    build: {
        sourcemap: true
    }
}
```

maps are generated but have a slight offset.

### Reproduction

https://github.com/antfu/vitesse

### System Info

```Shell
System:
    OS: Windows 10 10.0.22000
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
    Memory: 33.67 GB / 63.78 GB
  Binaries:
    Node: 19.7.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.5.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (111.0.1661.62)
    Internet Explorer: 11.0.22000.120
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
How do you identify it's an issue of vite-ssg? Have you tried to narrowing down and find the cause?

**Comment by OrbisK** [comment]
> How do you identify it's an issue of vite-ssg? Have you tried to narrowing down and find the cause?

Not yet. I'll give it a try.

**Comment by OrbisK** [comment]
I removed `vite-plugin-vue-layouts`, now sourcemaps are working. Ill open a separate issue there.

**Comment by OrbisK** [comment]
see https://github.com/JohnCampionJr/vite-plugin-vue-layouts/issues/108
