### ISSUE TITLE
build and dev error when trying to include includedRoutes from main.ts

### ISSUE THREAD

**Issue by jbaubree** [antfu/vite-ssg#344]
### What i want to do
Use of environment variables managed by Vite following [README#custom-routes-to-render](https://github.com/antfu/vite-ssg#custom-routes-to-render)

### How i do it
Based on [vitesse](https://github.com/antfu/vitesse)
```
// main.ts
import { ViteSSG } from 'vite-ssg'
import App from './App.vue'
...
export const createApp = ViteSSG(
  App,
  ...
)
export function includedRoutes(paths: string[]) {
  return paths
}
```
```
// vite.config.ts
import { defineConfig } from 'vite'
import { includedRoutes } from './src/main'
...
export default defineConfig({
  ...
  ssgOptions: {
    ...
    includedRoutes,
    ...
  },
})
```
### Error encountered
```
// pnpm dev
No loader is configured for ".vue" files: src/App.vue
src/main.ts:5:16:
  5 │ import App from './App.vue'
```
```
// pnpm build
  let error = new Error(`${text}${summary}`);
              ^
Error: Build failed with 1 error:
src/main.ts:5:16: ERROR: No loader is configured for ".vue" files: src/App.vue
```

### My question
I am maybe doing something wrong but i don't know what. This is a problem for me now because i need to use queries to get blog data => i need to have `~/` alias, `import.meta.env` ... 
I hope someone has more information on this subject or can help me find a solution 

### Reproduction

based on vitesse adding previous code #how i do it

### System Info

```Shell
System:
    OS: macOS 13.2.1
    CPU: (8) arm64 Apple M2
    Memory: 1.43 GB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.8.0 - ~/.nvm/versions/node/v18.8.0/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.18.0 - ~/.nvm/versions/node/v18.8.0/bin/npm
  Browsers:
    Brave Browser: 110.1.48.164
    Chrome: 112.0.5615.137
    Firefox: 108.0.1
    Safari: 16.3
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by justinzpc** [comment]
could you offer a detail reproduction on codesandbox or stackblitz.com？

**Comment by jbaubree** [comment]
@justinzpc sure, you can clone https://github.com/jbaubree/vitesse and run `pnpm build` to see error

**Comment by justinzpc** [comment]
bro, i have found the problem ,you shouldn't export the "includedRoutes" fun from main.ts, move it to vite.config.ts plz,
<img width="502" alt="image" src="https://github.com/antfu/vite-ssg/assets/16377701/1ea85e55-9633-43bd-b032-640b1273f14b">
i got a little busy last week, i just have time to check these code today

**Comment by jbaubree** [comment]
I want to use `environment variables` or `~` alias in my includedRoutes function and i can't do that from vite.config.ts. This is why i export includedRoutes from main.ts i'm following [README](https://github.com/antfu/vite-ssg#custom-routes-to-render) 2nd part :
```
// main.ts

import { ViteSSG } from 'vite-ssg'
import App from './App.vue'

export const createApp = ViteSSG(
  App,
  { routes },
  ({ app, router, initialState }) => {
    // ...
  },
)
export async function includedRoutes(paths, routes) {
  // Sensitive key is managed by Vite - this would not be available inside
  // vite.config.js as it runs before the environment has been populated.
  const apiClient = new MyApiClient(import.meta.env.MY_API_KEY)

  return Promise.all(
    routes.flatMap(async (route) => {
      return route.name === 'Blog'
        ? (await apiClient.fetchBlogSlugs()).map(slug => `/blog/${slug}`)
        : route.path
    }),
  )
}
```
It's not working as expected

**Comment by justinzpc** [comment]
// Sensitive key is managed by Vite - this would not be available inside
// vite.config.js as it runs before the environment has been populated.

i thought these upon annotations means you needn't import "includedRoutes" to vite.config.ts and set it as property into the "ssgOptions"

**Comment by jbaubree** [comment]
@justinzpc i don't understand well what you mean, what should i do to use vite encironment in `includedRoutes` fonction?

**Comment by jbaubree** [comment]
Oh right ! Thank you @justinzpc ❤️
