### ISSUE TITLE
Path based SSG

### ISSUE THREAD

**Issue by husayt** [antfu/vite-ssg#35]
In the vitesse-ssr example for vite-ssr, they have a path based i18n.
for example, try 
https://vitesse-ssr.vercel.app/vi/
and 
https://vitesse-ssr.vercel.app/tr/

How can one achieve the same with vite-ssg. In fact that would be very nice to add to vitesse as well.

Thanks

**Comment by hannoeru** [comment]
I think you can use this: https://github.com/antfu/vite-ssg#custom-routes-to-render
with some vue-router meta to switch vue-i18n's language

**Comment by husayt** [comment]
@hannoeru thanks for suggestion, but I ended up using the similar technique to the one [here](https://github.com/frandiox/vitedge/blob/cd47ffd81b1400b1ac8e60c3fedd0677a6217678/src/vue/entry-client.js) and 'pagesDir' param of vite-plugin-pages e.g.
```
pagesDir: ["", ...SECONDARY_LOCALES].map((x) => ({
        dir: "src/pages",
        baseRoute: x,
      })),
```
