### ISSUE TITLE
Bump 'critters' dependency to 0.0.20

### ISSUE THREAD

**Issue by binaryfire** [antfu/vite-ssg#370]
### Clear and concise description of the problem

A new version of Critters has been released:

https://github.com/GoogleChromeLabs/critters/releases/tag/0.0.20

However it's throwing peer dependency warnings in npm:

<img width="508" alt="image" src="https://github.com/antfu/vite-ssg/assets/5361908/17bd6ee5-564e-4bd6-adc6-55946a399151">

### Suggested solution

Bump critters dependency version for vite-ssg

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by rezelute** [comment]
Same issue for me, its blocking me updating to the latest version of vite-ssg
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: vite-ssg@0.23.2
npm ERR! Found: critters@0.0.20
npm ERR! node_modules/critters
npm ERR!   dev critters@"0.0.20" from the root project
```

**Comment by antfu** [comment]
Bumpped.
