### ISSUE TITLE
lottie-web build ssg 报错Ω

### ISSUE THREAD

**Issue by OnePieceLiu** [antfu/vite-ssg#377]
### Describe the bug

[vite-ssg] An internal error occurred.
[vite-ssg] Please report an issue, if none already exists: https://github.com/antfu/vite-ssg/issues
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

TypeError: Cannot set properties of null (setting 'fillStyle')
    at /Users/liuzhang/Desktop/pro/exchange-web/node_modules/lottie-web/build/player/lottie.js:1320:21
    at /Users/liuzhang/Desktop/pro/exchange-web/node_modules/lottie-web/build/player/lottie.js:1323:6
    at /Users/liuzhang/Desktop/pro/exchange-web/node_modules/lottie-web/build/player/lottie.js:1540:4
    at /Users/liuzhang/Desktop/pro/exchange-web/node_modules/lottie-web/build/player/lottie.js:2:83
    at Object.<anonymous> (/Users/liuzhang/Desktop/pro/exchange-web/node_modules/lottie-web/build/player/lottie.js:5:3)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:169:29)

Node.js v18.18.1

### Reproduction

bug

### System Info

```Shell
mac
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
This is a bug/design choice that the package you are using is not compatible with running on Node (SSG/SSR). Please report to that package, or make your usage as client only.
