### ISSUE TITLE
import.meta.env is empty when vite-ssg build for server

### ISSUE THREAD

**Issue by hannoeru** [antfu/vite-ssg#4]
Also confirmed the same issue in latest vitesse.

version: 
- vite@2.0.0-beta.10
- vite-ssg@0.2.0

# Log
```
[vite-ssg] Build for server...
building for production...
"import.meta" is not available in the configured target environment and will be empty
13 |    setup(__props) {
14 |
15 |  if (import.meta.env.PROD) {
   |      ^
16 |    // in prod mode, enable intersectionObserver based pre-fetch
17 |    usePrefetch()
```

**Comment by antfu** [comment]
Not very familiar with it. Shouldn't `import.meta` be dev only? Also think you may need `process.env.NODE_ENV === 'production'`?

**Comment by hannoeru** [comment]
After read vite's source code,
I figure out the problem is that only es2020 support import.meta syntax,
in vite-ssg esbuild target to es2017 so I got this error.

In vite it will insert env to import.meta on both build and dev.

**Comment by antfu** [comment]
It's set to es2018 because #3. Maybe we can revert that and add a notation on README and package.json>engine, asking users to have Node >=14. Not on my laptop atm, would you mind to create a PR? Thanks.
