### ISSUE TITLE
Initial State

### ISSUE THREAD

**Issue by pantajoe** [antfu/vite-ssg#40]
Hello!

Many thanks for this awesome and very minimalistic SSG Plugin for Vite!

What I'm currently missing is the ability to set an initial state when generating static HTML similar to [frandiox/vite-ssr](https://github.com/frandiox/vite-ssr#ssr-initial-state-and-data-fetching):

I am using [Pinia](https://pinia.esm.dev/) as a store and [these steps](https://pinia.esm.dev/ssr/#state-hydration) are necessary during building, so my fetched content from an API can stored in Pinia and injected into the generated HTML as an initial state to avoid unnecessary load times in production.

However, config functions like `onBeforePageRender` or `onPageRendered` do not help as I cannot get access to the app's context, or rather the pinia store from the Vue app.

**Comment by antfu** [comment]
I am not that familiar with those, but maybe let's see in the PR if you are interested in make one. Thanks
