### ISSUE TITLE
build error with vite-plugin-svg-icons !

### ISSUE THREAD

**Issue by leosin** [antfu/vite-ssg#48]
ReferenceError: document is not defined

what's  that mean 

<img width="543" alt="ssg-er2" src="https://user-images.githubusercontent.com/3676670/120060543-fdbd6600-c08a-11eb-82d0-197c39774835.png">
<img width="538" alt="ssg-error" src="https://user-images.githubusercontent.com/3676670/120060544-fdbd6600-c08a-11eb-91dd-df616c190556.png">

**Comment by hannoeru** [comment]
vite-plugin-svg-icons didn't support SSG.

I think wrap `SvgIcon` with  https://github.com/antfu/vite-ssg#clientonly can solve this problem.

**Comment by haliuhei** [comment]
try [vite-svg-loader](https://github.com/jpkleemans/vite-svg-loader)

**Comment by Miguelklappes** [comment]
> 
> 
> try [vite-svg-loader](https://github.com/jpkleemans/vite-svg-loader)

That one is the same, there is no decent svg loader for Vite/Vue 3. Maybe I'll try to create a good implementation.
