### ISSUE TITLE
Custom div id support needed

### ISSUE THREAD

**Issue by uuau99999** [antfu/vite-ssg#52]
I want to have my custom id for my entry div instead of id 'app', but it seems that it was hard coded. However, there is an attribute called 'rootContainer' in options which can specific the entry id for client build but does not work in ssr/ssg build, which is pretty tricky.
Hope that vite-ssg could support such feature. Thanks.

**Comment by antfu** [comment]
https://github.com/antfu/vite-ssg/pull/39

**Comment by uuau99999** [comment]
> #39
"rootContainer" DOES NOT WORK in ssg/ssr build, but does work in dev mode.
