### ISSUE TITLE
tsx component error

### ISSUE THREAD

**Issue by LiuJiangshan** [antfu/vite-ssg#59]
throw error:“ReferenceError: __default__ is not defined”

I have added the plugin  @vitejs/plugin-vue-jsx.
vite.config.ts
```
import VueJsx from '@vitejs/plugin-vue-jsx'
export default defineConfig({
...
plugins: [VueJsx(), ...]
...
})

```
main.ts
```
import {ViteSSG} from 'vite-ssg/single-page'
import App from "./App";

export const createApp = ViteSSG(App)
```
App.tsx
```
import {defineComponent} from "vue";

export default defineComponent({
    render: () => <div>hello</div>
})

```

**Comment by xiaojun996** [comment]
use template🧐  don't use jsx

**Comment by LiuJiangshan** [comment]
I don’t use this library anymore, because Google already supports spa application SEO, but history api is needed.https://developers.google.com/search/docs/guides/javascript-seo-basics#use-history-api
