### ISSUE TITLE
Problem with "type" : "module" option in package.json

### ISSUE THREAD

**Issue by cimchd** [antfu/vite-ssg#61]
I have a project with es modules enabled in the package.json.

```json5
// package.json
{
  "name": "project",
  "type": "module",
  "dependencies:  {
    ...
  }
   ...
}
```

I ran the command `vite-ssg build`and got the following errot: `Error [ERR_REQUIRE_ESM]: Must use import to load ES Module`

I figured out the problem is that the generated file in the .vite-ssg-temp folder is a common.js file with file ending `.js`. I changed the file ending to `.cjs` and it worked for me.

**Comment by cimchd** [comment]
Added a pull request how I solved it in vite-ssg as an option without breaking changes.

**Comment by cimchd** [comment]
In the meantime i canceled my pr from above and instead changed the rollup options in `node/build.ts` to use .cjs instead of .js :

```js
      rollupOptions: {
        output: {
          entryFileNames: '[name].cjs',
        },
      },
```
If you want me to create a pr, just let me know.

**Comment by antfu** [comment]
That looks like a much better solution, PR welcome 👍

**Comment by cimchd** [comment]
Good idea. I used [read-pkg-up](https://www.npmjs.com/package/read-pkg-up ) package to determine the nearest package.json file. So we should not need an option for this.
