### ISSUE TITLE
Pass generated route to createApp()

### ISSUE THREAD

**Issue by husayt** [antfu/vite-ssg#63]
Vitessg calls `Fn(ctx)` for every route. It is useful to know which route is being generated from with fn. Is there a reason that `route` not passed to fn i.e. smth like this : `Fn(ctx,route)`

https://github.com/antfu/vite-ssg/blob/36b9e9f77e4f1efed64f7945e2295ef227da74c5/src/node/build.ts#L100

Thanks

**Comment by husayt** [comment]
Just to give some background:

suppose I have a bilingual website with `/ja/...` routes for japanese and  rest `/...` for english pages. I am using pinia and want to initialise the state differently for japanese and english pages. So what I need is during pinia initialisation to know the generated path, so if containes `/ja/` to act differently.

vite-ssg goes through all routes and calling ` routes.forEach(fn(ctx)` could instead do, what i did in [this pull request](https://github.com/antfu/vite-ssg/pull/64) or smth like that to pass route to the path.

but I have a feeling I am missing something, otherwise that would be done already or maybe there is even simpler route.

So question comes back to how do I pass routePath to pinia [here](https://github.com/antfu/vite-ssg/blob/main/examples/multiple-pages-with-store/src/main.ts)

**Comment by sibbng** [comment]
Can't you do that with `router.beforeEach`?
```ts
    router.beforeEach((to, from, next) => {
      const store = useRootStore(pinia)

      if(to.path.includes('/ja/'))
        store.initializeJA()
      else
        store.initializeEN()

      next()
    })
```
Example from https://github.com/antfu/vite-ssg/blob/main/examples/multiple-pages-with-store/src/main.ts#L23-L28

**Comment by husayt** [comment]
Yes, but that router event happens way down the line. We have the path way before.
