### ISSUE TITLE
[Bug Report] navigator is not defined

### ISSUE THREAD

**Issue by YunYouJun** [antfu/vite-ssg#74]
When i build [monaco-editor](https://github.com/Microsoft/monaco-editor) with `vite-ssg`.

I get `navigator is not defined`.

A recurring example: [web-resume](https://github.com/YunYouJun/web-resume)

```bash
git clone https://github.com/YunYouJun/web-resume
pnpm install
pnpm run build
```

```bash
ReferenceError: navigator is not defined
    at Module.<anonymous> (/Users/yunyou/github/pages/web-resume/.vite-ssg-temp/main.js:7987:19)
    at Module.o._compile (/Users/yunyou/github/pages/web-resume/node_modules/.pnpm/registry.nlark.com+jiti@1.10.1/node_modules/jiti/dist/v8cache.js:2:2778)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at __require (/Users/yunyou/github/pages/web-resume/node_modules/.pnpm/registry.nlark.com+vite-ssg@0.12.0_8be4ce4ce3ee9f8584c22c4e982f597c/node_modules/vite-ssg/dist/chunk-3FHQZVYO.js:22:12)
    at build (/Users/yunyou/github/pages/web-resume/node_modules/.pnpm/registry.nlark.com+vite-ssg@0.12.0_8be4ce4ce3ee9f8584c22c4e982f597c/node_modules/vite-ssg/dist/node/cli.js:140:52)
    at async Object.handler (/Users/yunyou/github/pages/web-resume/node_modules/.pnpm/registry.nlark.com+vite-ssg@0.12.0_8be4ce4ce3ee9f8584c22c4e982f597c/node_modules/vite-ssg/dist/node/cli.js:229:3)
error Command failed with exit code 1.
```

---

I try it, but it doesn't work.

```ts
if (typeof navigator !== 'undefined') {
  const monaco = await import('monaco-editor')
  console.log(monaco)
}
```

**Comment by userquin** [comment]
@YunYouJun use `typeof window !== 'undefined'` instead, on SSR/SSG `navigator` is not defined.

See https://github.com/antfu/vite-ssg/issues/21#issuecomment-862333958

**Comment by YunYouJun** [comment]
> @YunYouJun use `typeof window !== 'undefined'` instead, on SSR/SSG `navigator` is not defined.
> 
> See [#21 (comment)](https://github.com/antfu/vite-ssg/issues/21#issuecomment-862333958)

In fact, I tried to do it, but it didn't work either. （`typeof window !== 'undefined'`）

**Comment by userquin** [comment]
@YunYouJun I'll take a look at your repo...

**Comment by YunYouJun** [comment]
> @YunYouJun I'll take a look at your repo...

Thanks, main file is <https://github.com/YunYouJun/web-resume/blob/main/src/pages/editor.vue>.

**Comment by userquin** [comment]
@YunYouJun what are you using `npm`, `pnpm` or `yarn`? There is no lock file on your repo...

**Comment by YunYouJun** [comment]
> @YunYouJun what are you using `npm`, `pnpm` or `yarn`? There is no lock file on your repo...

Because lockfile is large and it is not a project that requires a fixed dependency, I ignored the lock file.

`Yarn` or `pnpm` is OK, I'm currently using `pnpm`.

**Comment by userquin** [comment]
@YunYouJun I have your repo build working:

Change `serve script` with: `"serve": "vite preview"` (remove the hyphen).

Change `src/pages/editor.vue` just remove `import * as monaco from 'monaco-editor'` and `onMounted` configure this:

```ts
onMounted(async() => {
  const txt = await useResume(route.query.url as string)
  resumeTxt.value = txt
  console.log(txt)
  if (typeof window !== 'undefined' && container.value) {
    const monaco = await import('monaco-editor')
    monaco.editor.create(container.value, {
      value: resumeTxt.value,
      language: 'yaml',
      theme: 'vs-dark',
      wordWrap: 'on',
    })
  }
})
```

Since we are using `monaco editor` we need to change rollup options on `vite` config file: on SSG build the monaco dep will go to the temporary `main.js (5MB)` (the entry point for `vite-ssg` for build) and then will fail, since there is some usage to detect browser:

```ts
// vite.config.ts
...
...
import path from 'path'

const prefix = 'monaco-editor/esm/vs'
// import yaml from '@rollup/plugin-yaml'

// https://vitejs.dev/config/
export default defineConfig({
  resolve: {
...
...
  build: {
    rollupOptions: {
      output: {
        inlineDynamicImports: false,
        manualChunks: {
          jsonWorker: [`${prefix}/language/json/json.worker`],
          cssWorker: [`${prefix}/language/css/css.worker`],
          htmlWorker: [`${prefix}/language/html/html.worker`],
          tsWorker: [`${prefix}/language/typescript/ts.worker`],
          editorWorker: [`${prefix}/editor/editor.worker`],
        },
      },
    },
  },

  // https://github.com/antfu/vite-ssg
  ssgOptions: {
    script: 'async',
    formatting: 'minify',

```

![imagen](https://user-images.githubusercontent.com/6311119/126869742-e98308e4-fdd5-4f76-b881-eb5b2842d02b.png)

**Comment by YunYouJun** [comment]
It works. Thank you very much!

**Comment by YunYouJun** [comment]
Is it possible for us to do this automatically with vite-ssg? For example, detects the 'worker .js' suffix name when packaging.

**Comment by userquin** [comment]
@YunYouJun https://github.com/vitejs/vite/discussions/1791#discussioncomment-320938

**Comment by userquin** [comment]
@YunYouJun the problem is that we don't know if the worker is pre-bundled or not so the problem is on the user land, we cannot assume all workers requires pre-bundle them.

**Comment by YunYouJun** [comment]
Okay, I see.
