### ISSUE TITLE
Vue Router Warn when changing base path

### ISSUE THREAD

**Issue by Apostolique** [antfu/vite-ssg#84]
Let's say I change the base path to `/super/` for the example project "[multiple-pages](https://github.com/antfu/vite-ssg/tree/main/examples/multiple-pages)":

```ts
// main.ts
// ...
export const createApp = ViteSSG(App, { routes, base: '/super/' })
```

During build, I get this warning multiple times:

> [Vue Router warn]: No match found for location with path "/super/"

If I look at the generated HTML for `index.md` which becomes `index.html`, I see that the links end up as (manually added newlines so that it's easier to read):

```html
<a href="/super//a" class="">/a</a>
<br />
<a href="/super//b" class="">/b</a>
<br />
<a href="/super//nested/deep/b" class="">/nested/deep/b</a>
```

---

If I instead use:

```ts
export const createApp = ViteSSG(App, { routes, base: '/super' })
```

```html
<a href="/super/a" class="">/a</a>
<br />
<a href="/super/b" class="">/b</a>
<br />
<a href="/super/nested/deep/b" class="">/nested/deep/b</a>
```

I guess those links look ok, but I still end up with this warning:
> [Vue Router warn]: No match found for location with path "/super"

---

Without changing the base path, the links look like this:

```html
<a href="/a" class="">/a</a>
<br />
<a href="/b" class="">/b</a>
<br />
<a href="/nested/deep/b" class="">/nested/deep/b</a>
```

**Comment by aimergenge** [comment]
@Apostolique Hey bro, why not submit a PR, I think you are right!

**Comment by Apostolique** [comment]
I was mostly waiting for a response from @antfu in case I missed something. It didn't matter much to me since at the time I had my own fork but eventually migrated to <https://github.com/11ty/eleventy/> instead since it's better to make static sites. It also works with Vue / Vite if needed.

I don't have access to a computer for a few more weeks so feel free to submit one yourself if you want.
