### ISSUE TITLE
How to disable hydrate and router like in SvelteKit?

### ISSUE THREAD

**Issue by mzaini30** [antfu/vite-ssg#86]
In SvelteKit, I can disable both with this:

```javascript
import adapterStatic from '@sveltejs/adapter-static'

/** @type {import('@sveltejs/kit').Config} */
const config = {
    kit: {
        // hydrate the <div id="svelte"> element in src/app.html
        target: '#svelte',
        adapter: adapterStatic(),
        appDir: 'svelte',
        router: false,
        hydrate: false
    }
};

export default config;
```

What about in Vite SSG? Thanks.

**Comment by antfu** [comment]
To disable router: https://github.com/antfu/vite-ssg#single-page-ssg

Why would you want disable hydration?

**Comment by mzaini30** [comment]
@antfu I want only HTML and CSS (no JS) for webview in Android app

**Comment by userquin** [comment]
@mzaini30 on android webview you can also run JS, I have a working example with an app built with vite-ssg (vitesse template) using it and serving assets from android www/assets directory (bundle on the APK), and works also with modules:

![imagen](https://user-images.githubusercontent.com/6311119/131225381-ef21d279-e2e6-475c-a454-0028f54be209.png)

![imagen](https://user-images.githubusercontent.com/6311119/131225417-d7a2c18f-9fdb-4c07-8c9f-8e3a6c3739c4.png)

![imagen](https://user-images.githubusercontent.com/6311119/131225430-c3fa846e-b710-4915-9aa8-22ed9c5135db.png)

**Comment by antfu** [comment]
> @antfu I want only HTML and CSS (no JS) for webview in Android app

Then you can you can run a post script to remove all the script tags as you want. I would think this is out-of-scope of this project.
